### ISSUE TITLE
Custom URLs to list authors' posts

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Articulate#10]
Such as:

/authors/shannon

would list all posts by shannon

**Comment by vincentparrett** [comment]
+1 this is a feature we have on our current blog platform (Live blogs on dotnetnuke) and there a bunch of inbound links I would like to keep!

**Comment by biapar** [comment]
Is there or not this function?

**Comment by samgooch** [comment]
+1

**Comment by abhilashca** [comment]
@Shazwazza Can you list down the steps or pointers to achieve the same so that we can give it a try building the same?
Thanks.

**Comment by Shazwazza** [comment]
This is all done with this: https://github.com/Shazwazza/Articulate/pull/210
