### ISSUE TITLE
Creating Intro Image issue

### ISSUE THREAD

**Issue by kershnerd** [Shazwazza/Articulate#101]
I am trying to create a way to optionally render a blog intro image.

In the Settings->Articulate Post, I added a an Intro Image (of time Media Picker aliased as introImage) to the Post Attributes properties.

In the list.cshtml, I am trying to access that property like this:
```
@if (post.introImage)
{
<div class="post-image">
	<a href="{link will go here}" data-rel="prettyPhoto">
		<span class="img-hover"></span>
		<span class="fullscreen"><i class="fa fa-search"></i></span>
		<img src="[image will go here}" alt="">
	</a>
</div>
}
```
I get the error introImage is not a property of post (where post is in a foreach of type post in `Model.Children<PostModel>`).

What might I be doing wrong?

**Comment by kershnerd** [comment]
I was able to figure this out.  In the list view, I iterate over the posts and pullout the image property by doing `post["property id"];`

Like this:

```
@foreach (var post in Model.Children<PostModel>())
{
	<article class="post hentry">
		@if (post.HasValue("introImage"))
		{
		var image = Umbraco.Media(post["introImage"]);
		<div class="post-image">
			<a href="@image.Url" data-rel="prettyPhoto">
				<span class="img-hover"></span>
				<span class="fullscreen"><i class="fa fa-search"></i></span>
				<img src="@image.Url" alt="">
			</a>
		</div>
		}
```

**Comment by Shazwazza** [comment]
Remember that the Model used by Articulate is the normal IPublishedContent model that is used in Umbraco, so you can access any property data the normal Umbraco way. Normally property data access is done with the `Model.GetPropertyValue<T>("propertyName")` method, but in your case the value access done with `Model["propertyName"]` will also work (that might not work in some cases if the property is storing complex data)

**Comment by Shazwazza** [comment]
It's also worth noting that this feature is coming: https://github.com/Shazwazza/Articulate/issues/80
