### ISSUE TITLE
Hit Counter or Post View Counter

### ISSUE THREAD

**Issue by vincentparrett** [Shazwazza/Articulate#106]
Does Articulate have any way of counting how many times a post has been viewed? This is something we have in our current platform, and it's very useful for authors to guage what's popular. Yes I can use GA to look at the data, but that's not useful for authors. I couldn't find anything in the source or the doco.

I'm still getting my head around the source, and may be able to contribute a pr with this, just might need some pointers on where might be the best place to add this.

**Comment by vincentparrett** [comment]
I notice that so far, articulate doesn't do any db access, everything is via the core api. Do you have anything against hitting the db or was it just not needed with the current design? I can't see a way to do the view counter without using the database, would you accept a pr that does hit the db? 

My plan is to add a db table which holds the post id and an integer count, and just increment it when the post is viewed and add the result to the postmodel. I guess I would also need to add events to deal with posts being created and deleted, and perhaps also provide a way to reset the view count for a post. It doesn't look to be too difficult, if I could just get the dev environment working.

**Comment by Shazwazza** [comment]
Yes, you would need a custom table to track this. You cannot do hit counters with published content - it would destroy all performance of your website ;)

Unfortunately in the core we don't yet have correct package migrations which we'd need to implement in order for people to upgrade to use something like this but we can discuss that at a later time :)

**Comment by biapar** [comment]
+1
