### ISSUE TITLE
Set up project against Umbraco 7.3

### ISSUE THREAD

**Issue by vincentparrett** [Shazwazza/Articulate#107]
I forked the repo, cloned to my dev machine, loaded up in VS2015, ran nuget restore. The articulate.web project has an invalid reference to ClientDependency.Core.Mvc. Removed that, compiles fine but errors at runtime on 

 @using ClientDependency.Core.Mvc 
Articulate.Web\umbraco\Views\Default.cshtml    Line: 5 

Unistalled ClientDependency & ClientDependency.Mvc, compiles and runs... but couldn't find the db.. cleared out the connection string and restarted... get the umb "looks like there is still work to do" page, click on the "setup your new webisite button", sends me the backofifice login page.. but I have no idea what to enter there.. there's no db yet so how do I login? 

I'm an experienced mvc developer, but an umbraco noob, I've been using the 7.3RC and 7.3 release for development so far ad not had any real issues with it.

**Comment by Shazwazza** [comment]
Articulate has not been built against 7.3 so there will be issues getting it to work nicely unless you follow some important steps. 

Articulate from Nuget will work with 7.3 even though it's built against < 7.3.

I might find some time in the next couple of weeks to upgrade the project but we'll see. 

You should have a look at the Nuget dependencies for 7.3 and compare them to the ones listed for Articulate and you'll probably see what you are missing.

**Comment by vincentparrett** [comment]
Actually my dev environment for articulate is just a clone of this repo, so it's still using 7.2.8, I just couldn't get to a point where I could login. I'd like to make some mods (like a hit/view counter for posts) so I need to be able to compile and hopefully submit pr's if my mods are of use to others. 

I mentioned 7.3 because I have been working with it for a week, and had some success in creating my own controllers etc.

**Comment by Shazwazza** [comment]
I just wonder though if this repo downloaded the 7.3 targets from Nuget instead of 7.2.8 since it's probably configured to just use the latest 7.x ?

**Comment by vincentparrett** [comment]
No I verified that it was using 7.2.8. I'll come back to this in a week or two, busy converting my online store to umb (from dnn) and learning about umb in the process, hopefully I will have a better idea of what I am doing by then.
