### ISSUE TITLE
Integrating into an existing site?

### ISSUE THREAD

**Issue by vincentparrett** [Shazwazza/Articulate#114]
Can anyone provide advice on how to integrate this package into an existing site. The issue I have is that it's designed to have it's own master layout, with it's own model (IMasterModel), which makes it near impossible to integrate into an existing site with it's own theme. I have the same issue with Dialogue, which appears to have borrowed it's theme code from Articulate. 

To both Articulate and Dialogue to a site seems like I will have to duplicate a lot of the layout, content, css etc. Surely there must be a better way.

**Comment by Shazwazza** [comment]
Yes, IMasterModel implements IPublishedContent, so your layouts can just use IPublishedContent on your layout. There's quite a few posts on the forum about this.

**Comment by vincentparrett** [comment]
Not a very satisfactory setup though. That means that every other page loses the Umbraco helper and CurrentPage, unless they are instantiated everywhere, so on every view I end up with 

````var CurrentPage = Model.AsDynamic();````

on every view.. that's all good and well until I come across another package that requires something different. I'm not blaming you, this is something umbraco should be able to handle better. I'm just trying to find a better way to integrate Articulate and Dialogue into a site that has other packages, and a theme.

**Comment by Shazwazza** [comment]
Sorry I don't have much time to explain right now but what you want is perfectly possible. Also this is based on mvc architecture, not Umbraco. I will reply this week, but you can make your layout pages inherit from UmbracoTemplatePage<IPublishedContent> and you should be fine

**Comment by Shazwazza** [comment]
That html didn't come through, one sec....

**Comment by Shazwazza** [comment]
'''
UmbracoTemplatePage<IPublishedContent>
'''

**Comment by Shazwazza** [comment]
Argh.. This doesn't work from mobile. It's UmbracoTemplatePage OfType IPublishedContent (as a generic)

**Comment by vincentparrett** [comment]
Ah, got it, thank you. That's much better. Making progress now!
