### ISSUE TITLE
Articulate V 2.0.1 Source seems needs an easier/quicker way to get the test website running

### ISSUE THREAD

**Issue by terryclancy** [Shazwazza/Articulate#130]
I just downloaded Articulate V 2.0.1 Source and opened in in VS 2015 and tried to run in debug mode but got the error:

Umbraco cannot start. A connection string is configured but the Umbraco cannot connect to the database.     Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
 Exception Details: Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but the Umbraco cannot connect to the database.
Source Error: 
 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  
Stack Trace: 
[UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but the Umbraco cannot connect to the database.]

The connection string in Web.config is 

```
<add name="umbracoDbDSN" connectionString="Data Source=|DataDirectory|\Umbraco.sdf;Flush Interval=1;" providerName="System.Data.SqlServerCe.4.0" />
```

but that file(Umbraco.sdf)  does not seem to exist in the solution ??

Am I missing something here ?

Thanks

Terry Clancy

ClanceZ

**Comment by Shazwazza** [comment]
The source code isn't setup to already have a website. I don't want to commit databases and don't want to commit all of the Umbraco source files. I'll come up with a better solution eventually.

For now you can:

* Create a new Umbraco instance (however you'd normally prefer to do that)
* Install Articulate via the back office

Then, you can copy over all of the files/folders for your website on top of the Articulate folder /src/Articulate.Web - but don't overwrite the folders:

* ~/config
* ~/App_Plugins/Articulate
* ~/Properties

Then start the web project

**Comment by terryclancy** [comment]
OK thanks for the guidance.  I'll let you know how I go.

Terry Clancy

ClanceZ

**Comment by Shazwazza** [comment]
I've added instructions on getting setup with the source to the readme: https://github.com/Shazwazza/Articulate
