### ISSUE TITLE
Could not load file or assembly 'System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by kurt1288** [Shazwazza/Articulate#137]
I'm trying to get Articulate to work on an existing Umbraco installation. When I navigate to the blog URL, I get the following error:

`Could not load file or assembly 'System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.`

The Umbraco version I'm using is 7.2.8. So what am I missing here? Do I need to manually update the Razor dll (which I'm hesitant to do)? Should I just redirect the version 3 to whatever version I have in the bin folder (seems unlikely)?

**Comment by Shazwazza** [comment]
Hi, Articulate requires 7.3 at a minimum, see release notes fro version 2.0: https://github.com/Shazwazza/Articulate/releases/tag/v2.0.0

I will update the docs to make this more clear.
