### ISSUE TITLE
Tag/Category links on different domain giving a 404 not found page

### ISSUE THREAD

**Issue by ukdiverboi** [Shazwazza/Articulate#141]
I am using version 1.0.9 I have a blog under two separate language nodes, such as:

EN
---Blog
ES
---Blog

The Spanish node has two hostnames associated with it, e.g.

atmos.otbdigital.co.uk
atmosila.otbdigital.co.uk

The English version works perfectly however on the Spanish version if I view a blog post, then click a related category or tag link, I am returned a 404 not found error. 

I have setup two different data types for the Spanish tags and categories so they are distinct from the English tags.

Example links from staging site that work/don't work

**Work**
http://atmos.otbdigital.co.uk/blog/categories/Pipeline%20industry 
http://atmos.otbdigital.co.uk/blog/tags/costa%20rica

**Don't Work**
http://atmosila.otbdigital.co.uk/blog/categories/Spanish%20Category
http://atmosila.otbdigital.co.uk/blog/tags/spanish%20tag

**Comment by jwarran** [comment]
Hi,

We are using Articulate v 2.0.2 and the issue still remains. I'm not sure if this functionality is required for some other reason. Is there a reason for specifically throwing the not found exception in ArticulateTagsController rather than just returning zero results? 

Cheers,

**Comment by ukdiverboi** [comment]
Good morning, Is there an update on this issue and any idea when it may be fixed? Thanks

**Comment by Shazwazza** [comment]
The problem is due to multiple hostnames. 

I'm not sure when I'll have time to look into this so I can't unfortunately provide you with any timeframe, hopefully soon, but this depends on my current workload.

**Comment by Shazwazza** [comment]
Fixed in 2.0.4: http://bit.ly/29beB49
