### ISSUE TITLE
Articulate is SEO Friendly?

### ISSUE THREAD

**Issue by biapar** [Shazwazza/Articulate#143]
Articulate is SEO Friendly?

**Comment by Shazwazza** [comment]
Yes, yes it is. If you would like more information please phrase your questions more descriptively.

**Comment by biapar** [comment]
Hi,
Like: canonical url, keywords and descriptions, alt tag, alternate link, image alt tag...

**Comment by Shazwazza** [comment]
- canonical url **Yes**
- keywords and descriptions **Yes**
- alt tag - for what exactly?
- alternate link - this depends if you need/want them and if you have alternate links, but **Yes** you have full control over the markup rendered
- image alt tag **Yes** If you use the Umbraco back office you can compose posts with the Rich Text Editor or the Markdown Editor which both allow you to insert images with alt tags/etc.. If you use LiveWriter, this allows you to specify alt text. If you use Articulate's mobile friendly post editor which uses Markdown which allows you to specify alt text

**Comment by biapar** [comment]
alt tag - for what exactly? sorry is an error typo..I wish to write title tag for href.

**Comment by Shazwazza** [comment]
Sure - you can do anything you want. Umbraco does not restrict you by any means with regards to the HTML output. Articulate uses Umbraco, so it can do all of that stuff. If you use Markdown, Rich Text or LiveWriter then of course you can add a title tag.
