### ISSUE TITLE
Getting The route URL separator character '/' cannot appear consecutively error with Articulate 1.0.9

### ISSUE THREAD

**Issue by goverdhang** [Shazwazza/Articulate#144]
Hello,

   I browsed around and saw that this error has happened in earlier versions of Articulate. I saw issue #50 as well. But, I am seeing the same error with Articulate1.0.9. My umbraco version is 7.2.8. Please help!!

Error:
The route URL separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
Parameter name: routeUrl

**Comment by Shazwazza** [comment]
I haven't seen this error for many versions now and i'm pretty sure it was fixed with some other bug fixing when dealing with multi-tennant/domains
