### ISSUE TITLE
Leftovers in uSync folders, after uninstalling articulate package

### ISSUE THREAD

**Issue by panayis** [Shazwazza/Articulate#149]
Hello,
   I am not sure if i should be posting this, however, I faced an issue after uninstalling articulate package from Umbraco backoffice. There are some left-overs in the uSync folders. This caused the website url and also the website backoffice url to show exception [Exception: No ContentType matching the passed in Alias: 'Articulate' was found].
   The problem was solved after I removed folder [uSync\data\Content\blog] and also removed any folders related to articulate document types within my home folder like [uSync\data\Content\home\blog].
That's all,

P.

No ContentType matching the passed in Alias: 'Articulate' was found

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: No ContentType matching the passed in Alias: 'Articulate' was found

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[Exception: No ContentType matching the passed in Alias: 'Articulate' was found]
   Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup() +672
   Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +316
   Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +37
   Umbraco.Core.CoreBootManager.<Complete>b__a(IApplicationEventHandler x) +230
   Umbraco.Core.EnumerableExtensions.ForEach(IEnumerable`1 items, Action`1 action) +141
   Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete) +293
   Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete) +114
   Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e) +234
   Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e) +34

[HttpException (0x80004005): No ContentType matching the passed in Alias: 'Articulate' was found]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9941577
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +339
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): No ContentType matching the passed in Alias: 'Articulate' was found]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9923088
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +90
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

**Comment by Shazwazza** [comment]
I'm not very familiar with uSync or how it works but this issue would be related to that and not Articulate. Articulate doesn't know anything about uSync so I would recommend getting in touch with the owner of that package and describe your issue there.
