### ISSUE TITLE
Feature Request: Subscribe to Updates (by Email)

### ISSUE THREAD

**Issue by hyrmedia** [Shazwazza/Articulate#153]
It's common for many blogs to have a "subscribe" feature that allows visitors to subscribe and receive notifications when new posts are added, or a summary of the latest posts on a recurring basis, something of that nature.

We had this with our former blog, so I'd love to see this feature added to Articulate at some point.

**Comment by simonech** [comment]
I think this is there already, using the RSS feed.

**Comment by hyrmedia** [comment]
@simonech - I'm not talking about subscribing to an RSS feed, I know Articulate supports that.

I'm talking about a visitor entering their email address into a small form on the website, and then receiving emails in their inbox notifying them whenever a new blog post is added (but ideally supporting e.g. weekly summaries as well).

RSS is something totally different, users have to know what RSS is and how to subscribe, and it's got nothing to do with Email (although many email clients are RSS readers as well).

**Comment by hyrmedia** [comment]
Note: Articulate doesn't have to provide the form itself, of course. It could just pull from an arbitrary list of email addresses.

**Comment by kirkholt** [comment]
MailChimp support [RSS-to-Email](https://mailchimp.com/features/rss-to-email/)

**Comment by Shazwazza** [comment]
Closing this issue since this can be acheived outside of Articulate
