### ISSUE TITLE
After Installing articulate Error is dispaly even thought i have upgraded umbraco 7.1.3 to 7.3.2

### ISSUE THREAD

**Issue by hiranmaisomarajupalli** [Shazwazza/Articulate#155]
Find attached screen shot
![error while installing articulate](https://cloud.githubusercontent.com/assets/20723459/17330701/733db712-58e5-11e6-8418-b267bcded0f5.png)

**Comment by hiranmaisomarajupalli** [comment]
Any one reply regarding this issue

**Comment by Shazwazza** [comment]
This is an Umbraco issue, has nothing to do with Articulate.

It is looking in the wrong place for the package.xml file, not sure if you have some custom configuration on your website. If you have steps to replicate, then please log an issue on the Umbraco tracker. 

Not sure why you are upgrading to 7.3.2, there's plenty of newer and less buggy versions than that. You should upgrade to the latest version of Umbraco. Even in the 7.3.x series there are tons of issues fixed after 7.3.2: https://our.umbraco.org/contribute/releases/compare but you should really just upgrade to the latest 7.5.x version.
