### ISSUE TITLE
How to disable ClientDependency.Core.Mvc

### ISSUE THREAD

**Issue by claire-james-infotrack** [Shazwazza/Articulate#156]
Hi,

I have installed the articulate plug in and would like to use the theme VAPOR as a base for my blog. I have tried editing the css file 'screen.css', but all styling information is replying on a dependancy handler. Could you advise how to remove this dependancy so that I can add custom fonts, change font colours etc.

Many thanks

![screen shot 2016-08-08 at 11 19 13 am](https://cloud.githubusercontent.com/assets/20717240/17466830/35b47510-5d5a-11e6-8a8b-27a2f68214e0.png)
![screen shot 2016-08-08 at 11 20 29 am](https://cloud.githubusercontent.com/assets/20717240/17466834/3ea623ee-5d5a-11e6-9982-dd8ec6221fc4.png)

**Comment by Shazwazza** [comment]
Hi, Articulate uses ClientDependency (CDF) to load in it's assets. This is totally optional but by doing so does the bundling/minification for you.  CDF is enabled when debug=false in your web.config, if you enable debug then bundling/minification is turned off. When you deploy new changes to your JS/CSS to production, you need to change the CDF version in the /config/clientdependency .config file (to anything really) which will clear both the server and client side caches. CDF docs are here: https://github.com/shazwazza/clientdependency

You can see the Vapor theme's dependency declarations here: https://github.com/Shazwazza/Articulate/blob/master/src/Articulate.Web/App_Plugins/Articulate/Themes/VAPOR/Views/Master.cshtml#L27

So if you want to keep using CDF, just change the declarations. `@Html.RenderCssHere()` and `@Html.RenderJsHere()` are then used to render the link/script blocks.

If you don't want to use CDF for this, then just remove these declarations and render your script/link tags however you like.
