### ISSUE TITLE
Archive and Tags not working when Umbraco running as a virtual directory

### ISSUE THREAD

**Issue by nwr100** [Shazwazza/Articulate#159]
I have installed Umbraco as a sub application within my main non CMS web site. Base URL for Articulate blog looks something like http://mymainsite.com/blog. This works fine apart when I click  http://mymainsite.com/blog/tags or http://mymainsite.com/blog/categories.

All works fine when not running as a subsite in IIS.

Thanks & Regards
Nigel

**Comment by nwr100** [comment]
For anyone else who stumbles across this issue, I found a solution by making sure the IIS sub application directory was not included in the nodeRoutePath in ArticulateRoutes.cs. The routing needs to be registered for just /tags not /[sub site directory/tags

**Comment by ukdiverboi** [comment]
Hello, I am having the same problem you outlined above, can you tell me how you made sure the IIS sub application directory was not included in the nodeRoutePath?? Can you provide me with a code example of what you altered?

**Comment by nwr100** [comment]
Hi, I downloaded the latest source for Articulate and in the ArticulateRoutes.cs I substituted the grouping.Key with an empty string

so was like this..

`MapRssRoute(routes, umbracoUrlProvider, grouping.Key , nodesAsArray);
MapSearchRoute(routes, umbracoUrlProvider, grouping.Key , nodesAsArray);                                        
MapTagsAndCategoriesRoute(routes, umbracoUrlProvider, grouping.Key , nodesAsArray);
MapMarkdownEditorRoute(routes, umbracoUrlProvider, grouping.Key , nodesAsArray); `

 and I made it like this

`var key = "";
MapRssRoute(routes, umbracoUrlProvider, key, nodesAsArray);
MapSearchRoute(routes, umbracoUrlProvider, key, nodesAsArray);                                        
MapTagsAndCategoriesRoute(routes, umbracoUrlProvider, key, nodesAsArray);
MapMarkdownEditorRoute(routes, umbracoUrlProvider, key, nodesAsArray);`

 Hope this helps!

**Comment by Shazwazza** [comment]
Not sure why this was closed, this certainly seems like an issue that should be fixed. I'll investigate when i get time.
