### ISSUE TITLE
Tags and Categories issue with domain path suffixes

### ISSUE THREAD

**Issue by craigs100** [Shazwazza/Articulate#161]
Ref: https://our.umbraco.org/projects/starter-kits/articulate/discussions/79901-how-to-get-tags-and-categories-pages-working

For a multi-tenanted site, during development using VS2015 and running on inbuilt IISExpress, adding a hostname suffix to the second site causes the failure of Tags and Categories pages. The first site will work, the second site gives a 404.
1st site hostname: localhost:1234, Lang: en-gb
2nd site hostname: localhost:1234/somesite, Lang: en-gb

Not sure if this is still an issue if the difference is just the Language and Culture setting. Only way to "fix" it was to split the two sites into their own Umbraco installations.

**Comment by philius44** [comment]
I am running into the very same Problem due to site.com/de, site.com/ hostnames. 
Tags and Category Links are working in just one of both hostnames.

Are, in the meantime, other solutions available than splitting up the Umbraco installation?

**Comment by Shazwazza** [comment]
@philius44 please always make sure you list what versions you are using. What version of Umbraco and Articulate are you using?

**Comment by philius44** [comment]
Umbraco 7.5.8 and Articulate 2.0.5

**Comment by Shazwazza** [comment]
Can you verify that issue in 3.0.0 ? There's a tremendous amount of fixes applied to that version. I am unable to maintain older Articulate versions

**Comment by maxemilian** [comment]
Hi Shazwazza
First of all: thank you for providing free software.
We run into problems after upgrading to Umbraco 7.15.3. 
Your software works well, except with Tags and Categories. Articles do not show up on the tags and category pages, although the content looks good.
After clearing caches and restarting the application pool, no article shows up when selecting a category. After saving and publishing an article, articulate displays the document under the category listing. Also, the export only contains the freshly saved article. When restarting the application pool, everything is gone again. This cannot be achieved with re-publishing the content. It must be saved and published. 

I guess you hook on the save function and alter your caches to reflect the latest changes to the content. It looks like the initialization method does not work anymore, where you initially build your blog cache.
We had this issue with 2.x of articulate, and the upgrade to 3.0.2 did not improve the situation. 
How can I check the initialization functionality and configuration? 

Thank you
Max

**Comment by Shazwazza** [comment]
@maxemilian thanks for the report ... i just need a bit more info, are you saying the tags/categories pages return a 404 or return a page without anything listed in there? 
If you want to help debug you can clone this repository and build it (for v7 you'll have to update to one of the release tags for the articulate version you are using). You can build the solution and then drop the dll into your site and then from the articulate vs solution you can attach to your running iis/issexpress process.

**Comment by maxemilian** [comment]
@Shazwazza thank you for the quick reply. I get a category page without articles (except the ones recently saved). Also, the xml export does not contain category mappings to the articles (except the ones mentioned). 
Attaching to the live machine is not possible, but I will set up a test environment.
Prior to debugging: how can I verify that the initialization process works correctly? As far as I have seen, the software initializes caches during the application startup. Maybe there is something broken.

**Comment by maxemilian** [comment]
It looks like this is an umbraco problem (which might be limited to this installation which was upgraded several times). 
I figured out, that helper.TagQuery.GetAllContentTags("ArticulateCategories") does not return all categories, and Umbraco.GetContentByTags(rootPageModel, tagGroup, baseUrl) does not return all posts of a category. 
I will work on this issue with Umbraco. Thank you for your input ;)

Max

**Comment by maxemilian** [comment]
Thanks again for your quick reply. After debugging all of it with the remote debugger, I figured out that something during an upgrade process created a new tag group 'default' with all of the tags and categories defined. Umbraco seems to just take the first it finds, and Articulate sends the group defined ('ArticulateTags' or 'ArticulateCategories'). This was the reason, it didn't display the posts.

After fixing the data, it worked like charm.

UPDATE
    cmsTagRelationship
SET
    cmsTagRelationship.tagId = a.id
FROM
    cmsTags a
    INNER JOIN cmsTags b 
        ON a.tag = b.tag
		and a.[group] = 'ArticulateTags'
		and b.[group] = 'default'
WHERE
    b.id = cmsTagRelationship.tagId



UPDATE
    cmsTagRelationship
SET
    cmsTagRelationship.tagId = a.id
FROM
    cmsTags a
    INNER JOIN cmsTags b 
        ON a.tag = b.tag
		and a.[group] = 'ArticulateCategories'
		and b.[group] = 'default'
WHERE
    b.id = cmsTagRelationship.tagId

-- just execute when you are sure you're not using tags anywhere else
-- delete from cmsTags where [group] like 'default'

**Comment by Shazwazza** [comment]
Interesting, so this is an issue with the Umbraco upgrade process? Any chance you know where this all goes wrong?

**Comment by maxemilian** [comment]
It’s challenging to figure out the real source of the problem. 

 

It’s essential to check the wording of the group field, and if the categories and tags are redundant within the database. Having redundant categories with different group fields leads to inconsistency. 

 

Max

 

 

 

Von: Shannon Deminick <notifications@github.com> 
Gesendet: Montag, 2. März 2020 00:59
An: Shazwazza/Articulate <Articulate@noreply.github.com>
Cc: Maxemilian Hilbrand <maxemilian.hilbrand@isicore.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Shazwazza/Articulate] Tags and Categories issue with domain path suffixes (#161)

 

Interesting, so this is an issue with the Umbraco upgrade process? Any chance you know where this all goes wrong?
