### ISSUE TITLE
RSS Feed not working

### ISSUE THREAD

**Issue by BobcatProgrammer** [Shazwazza/Articulate#162]
I have a Umbraco install (7.5.2) with 4 root pages with different domains assigned. within the main page there is an articulate blog (2.0.5).
The blog works fine, but the rss feed displays an error message:
`Die gesuchte Ressource wurde entfernt oder umbenannt, oder sie steht vorÃ¼bergehend nicht zur VerfÃ¼gung.` which translates to `The resource has been removed or rennamed, or is temporarily not available`
 Is this a bug or have I misconfigured something?

Thanks,
Simon

**Comment by SimonTrockel** [comment]
Hi Shannon,
can you help with this please?

Thanks a lot!
Simon

**Comment by Shazwazza** [comment]
I know this is old and sorry about that! Any chance you've try the latest versions of Articulate/Umbraco, i don't see this issue with any of my tests or other folks' live sites so would needs steps to replicate.

**Comment by SimonTrockel** [comment]
Currently moving my stuff to umbraco cloud. After that I will try again. This will take 3-4 weeks so please be patient :)

**Comment by Shazwazza** [comment]
Closing this issue if you need to reopen please include steps to replicate.
