### ISSUE TITLE
Single instance of controller cannot be used to handle multiple requests

### ISSUE THREAD

**Issue by nickyBaker** [Shazwazza/Articulate#163]
This is the error I am getting: 'A single instance of controller 'Articulate.Controllers.ArticulateController' cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request.'

I am trying to add the plugin to a pre-existing Umbraco project (umbraco version 7.2.8 and Articulate version 1.0.9). List and Post views have been changed to inherit 
@inherits Umbraco.Web.Mvc.UmbracoViewPage<IPublishedContent>
as your wiki suggests, and var articulateModel = (Articulate.Models.ListModel)Model; with the correct Model was added. 
Is there a solution for this controller error?

**Comment by Shazwazza** [comment]
I know this is a super old issue - very sorry about not being able to respond until now. I haven't heard of this error in any other installation and cannot replicate the problem.

I'll close this issue for now but if you can replicate it with the latest Articulate version please re-open with replication steps.

Again very sorry about not being able to keep up with issues posted here.
