### ISSUE TITLE
Image paths incorrect in Articulate-generated RSS feed

### ISSUE THREAD

**Issue by Nicole-P** [Shazwazza/Articulate#165]
All image links are broken in the rss feed due to the incorrect URL being prepended to image src's.  Here are the steps I took to reproduce the issue:
1. Clone down my existing site locally
2. Install Articulate through Umbraco Back-end. New Blog node shows up in the root of my content tree.
   ![image](https://cloud.githubusercontent.com/assets/22821130/19358439/c7cc679c-912a-11e6-9453-42e69a5d94f7.png)
3.  Edit "Test Post" to include image: upload image through the "insert image" button on the RTE.
4. Save and publish "Test Post"
5. Save and publish Blog node
6. Navigate to http://www.mydomain.com/blog - click to view "Test Post". Image shows up fine.
   ![image](https://cloud.githubusercontent.com/assets/22821130/19358666/9565cea0-912b-11e6-827e-d3d1464d2476.png)
7. Click the RSS icon at the top of the page- Image shows up broken in RSS feed due to incorrect url:
   ![image](https://cloud.githubusercontent.com/assets/22821130/19358745/e961f7ea-912b-11e6-93ea-39f93cda6b9c.png)

Please let me know if I can further clarify anything.

Thank you!

**Comment by simonech** [comment]
It looks like it's building the URL from the root of the blog node, while media's URL always starts from the site root.

**Comment by Nicole-P** [comment]
Hi! Any word on whether this has been looked at yet? It's preventing me from launching my blog :(

Thanks!

**Comment by martijn1k** [comment]
@Nicole-P 
You can change the relative image URL's in code view to absolute URL's as a work arround.
We've experienced the same issue.

Would be nice to have this fixed though ;)

**Comment by Nicole-P** [comment]
@martijn1k , thanks so much for responding! I'm fairly new to Umbraco - would you be able to give me a quick run-through on how you did this? Specifically I am wondering where I would find the code that you edited. Thanks again, really appreciate it :)

**Comment by martijn1k** [comment]
@Nicole-P Hey, sorry for the late reply!

You can do this inside the blog post rich text editor, so there is no technical knowhow required for this work-arround. Just open up the blog post you want to edit in Umbraco, and then press the code view. The icon looks like <> in the Rich Text Editor

If you're using Markdown, it's even easier, all the URL's are in the bottom of the blog post.

Look for paths that look like "/media/1234/imagename.jpg" and then change it to your full url (you can test the image in a new browser window) 

so for example: www.nicole-p.com/media/1234/imagename.jpg

Hope this clarifies it a bit. If not... let me know. Good luck

**Comment by Nicole-P** [comment]
@martijn1k 

Thanks for the response! I will do that for sure on new posts. My main problem is that I've imported an existing blog and all of the imported images have relative URLs, so I would have to go in and edit each image url manually for hundreds of posts!

However your post has made me rethink my choice to delay the launch of the blog - if the problem is only really apparent to email subscribers, and all future post images are fixed with the workaround you've described, then maybe it's not quite as important if all my past posts have broken images in the emails... 

Thanks for you input!

Hopefully this does get fixed in Articulate at some point though :)

**Comment by Nicole-P** [comment]
@martijn1k How did you configure the TinyMCE Rich text editor to not strip out the absolute image URLs? That's where I'm stuck now! Thanks again!

**Comment by Shazwazza** [comment]
@Nicole-P I need you to clarify the problem. Previously you mentioned that the problem exist with a brand new installation and just adding an image to a Post - the RSS images don't work for you - is this correct?

You've previously just mentioned that you've imported posts and the image paths are not correct - is this a new problem or the same problem? (It's worth noting that the blog import tool allows you to specify regex transforms for images found when importing: https://github.com/Shazwazza/Articulate/wiki/Importing#options)

**Comment by Nicole-P** [comment]
Hi @Shazwazza 

Thanks for your response! Sorry for the confusion- they are both the same problem. When I imported my blog I used regex to change all of the image paths, but I kept them all relative rather than absolute because I wanted the images to show on both my live and dev environments. Since all of the imported images are relative, they have the same problem where the wrong root is pre-pended to the url in the RSS feed.

I've created a workaround where I have a partial view macro for inserting images into the RTE which allows me to specify an absolute path for them. This is working so far, but it would be really nice to be able to use the native media addition in the RTE.

Thanks again Shannon!

**Comment by Nicole-P** [comment]
@Shazwazza Any info on when 3.0.0 will be released? Looks like the fix for this issue will be in there (yay!) and I would love to be able to tell my content editors when it's coming. Thank you!

**Comment by Shazwazza** [comment]
hopefully in the next few weeks ... hopefully i find some time

**Comment by littlenomads** [comment]
Did this issue get fixed.  I'm having the same issues with my site. RSS feeds Are not picking up the images. Using the articulate blog.

**Comment by Shazwazza** [comment]
The issue is marked fixed in 3.0.0, are you using 3.0.0?

**Comment by littlenomads** [comment]
Thanks @Shazwazza for getting back, I actually don’t think I am using the latest. I probably should upgrade, as would like to have ability to create full page blog articles, without sidebar.

**Comment by Shazwazza** [comment]
There's nothing stopping you from doing that in any version, you are in full control over the markup that is done, if you want to create your own theme from one that is shipped, just copy the theme folder and change any markup in razor files that you want. Themes are located /App_Plugins/Articulate/Themes

**Comment by littlenomads** [comment]
Thanks. I'm very much self-taught around umbraco. Have to get others in from time to time to help me out. With the site. Will see if I can someone to help with this and make sure the image and rss is working.  Thanks again.
