### ISSUE TITLE
Can't uninstall 2.0.5

### ISSUE THREAD

**Issue by craigs100** [Shazwazza/Articulate#166]
Umb 7.5.3, Articulate 2.0.5
Client removed the Articulate blog, archive and authors nodes from the content tree. When I came to uninstall the Articulate package I got an instant "Server error - Failed to uninstall package". The only thing in the log is "Mapping routes for 0 Articulate root nodes". The docTypes have been removed but that's about it. The Dev Dashboard  "Articulate Importer" is also still there. Thought about reinstalling to uninstall from a full install but can't as the project page states "Package already installed". I'm stuck.

**Comment by Shazwazza** [comment]
doh! that doesn't sound great. When i find some time i'll test it to see what is happening. 

In the meantime, you can manually delete it or you can modify your /app_data/packages/installed file and remove the articulate instance from there (or in theory you could change the version that is listed there to a previous one so umbraco thinks you are installing a newer one)

To manually uninstall is pretty easy:

* Remove articulate doc types
* Remove articulate data types
* Remove articulate DLLs
* Remove the articulate App_Plugins
* Remove the articulate dashboard from the dashboard config.

**Comment by craigs100** [comment]
Thanks Shannon. I removed it manually using the steps you said. :)

**Comment by Shazwazza** [comment]
I know this has taken far too long for me to get back to this, really sorry about that ! 

I will close this issue now since I've re-rested all of the above and uninstallation seems to work well with the latest Articulate version
