### ISSUE TITLE
Default order of results when searching is incorrect

### ISSUE THREAD

**Issue by darthglader** [Shazwazza/Articulate#168]
When performing a search for empty string all results are returned.  However the results are ordered by ascending date when they should be ordered by descending date as with all other queries.

e.g.   /blog/search?term=

I'm using 2.0.1 and have tested in the latest 2.0.5 and the issue is still there.

**Comment by Shazwazza** [comment]
The sort order of search results is based on score/relevance, there is no logic in Articulate to sort by dates for searching.

If we want to return the results for an empty search term and order by a date, then the Examine settings would need to be updated to ensure that  the date field we want to sort on (i.e. updateDate) is marked as sortable. Unfortunately by doing this means that the index set being used to search would need to mark this field as sortable and to do that would mean that all fields in the examine settings would need to be listed for inclusion. Ideally we could update the Examine APIs to mark fields as sortable via code so it doesn't need to be done in config.
