### ISSUE TITLE
Add Twitter/FB cards to skins

### ISSUE THREAD

**Issue by simonech** [Shazwazza/Articulate#170]
When sharing posts on twitter and facebook it would be great to have better sharing experience by implementing [OpenGraph Protocol](http://ogp.me/) for facebook and [Twitter Card](https://dev.twitter.com/cards/overview)

**Comment by skidmow** [comment]
Think I may have inadvertently tackled this here: #220

**Comment by Shazwazza** [comment]
Will close this  now, i've added these metatags to all themes now which uses an HtmlHelper to render, we can enhance the cards when we get more author info too but for now it's pretty good and it's a single line in the master template which will render the appropriate tags depending on if it's a blog post or regular page.
