### ISSUE TITLE
Disqus export is invalid when posts are not published

### ISSUE THREAD

**Issue by simonech** [Shazwazza/Articulate#179]
I just noticed that disqus comment export xml file is invalid when the export is done by not selecting "publish all" check box.
This is because the xml needs the absolute url of the post, which is only available when the post is published.

So, there are two options to solve the problem:
 1. make publishing compulsory if disqus export is selected
 2. publish and then unpublish the post after the export has been done.

Which is better?

**Comment by Shazwazza** [comment]
I think # 1 is easiest, if discuss export is selected we can auto select that and disable unselecting it
