### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by ismailmayat** [Shazwazza/Articulate#189]
Using umbraco 7.5.3 and articulate 2.0.5.  After installing the package i get error Could not load type 'Articulate.Controls.Installer'. ---> System.Web.HttpException

When i try to view doc type articulate i get error with articulate themepicker datatype clicking on that gives error. Looks like some of the default stuff it needs is missing

**Comment by Shazwazza** [comment]
Have you tried, uninstalling or removing articulate files and re-installing? or installing on a new vanilla 7.5.3 (or better yet 7.5.6) ?

**Comment by ismailmayat** [comment]
I turned on debug in web.config then installed and it worked.
