### ISSUE TITLE
Shouldn't default skin be Vapor?

### ISSUE THREAD

**Issue by simonech** [Shazwazza/Articulate#190]
According to [Installed Themes](https://github.com/Shazwazza/Articulate/wiki/Installed-Themes), the default skin should be VAPOR

>VAPOR
>
>This is the default theme installed, it is a very clean & simple responsive theme but supports more functionality of any of the other imported Ghost themes. Originally created by Seth Lilly

But the default skin installed is Shazwazza.

So, either the wiki has to updated, or the package installer fixed :smile:

**Comment by Shazwazza** [comment]
haha, ok will update the wiki :) Shazwazza is default just because it shows the most features

**Comment by Shazwazza** [comment]
Actually, i'll change it to be Vapor, it's a simpler more common skin

**Comment by simonech** [comment]
I guess this has been merged 😄
