### ISSUE TITLE
Add wide image size for blog post pic

### ISSUE THREAD

**Issue by simonech** [Shazwazza/Articulate#202]
@Shazwazza what do you think about adding a new cropper size to show the post pic above the title in wide format, instead of the not-so-nice small floating pic?

Would help make nicer graphic skins with bigger images.

**Comment by Shazwazza** [comment]
Otherwise you can always just generate a wide crop using the GetImageUrl method

**Comment by simonech** [comment]
Yeah, but with the crop size then users can modify the positioning if needed.
This is done in the installation phase I've seen, right?
This size could be also used by the social cards that usually need a bigger and landscape size

**Comment by Shazwazza** [comment]
This is done and implemented on all themes now and i've also added upgrade logic to add the additional crops. the crop aliases are now: square, thumbnail and wide  and wide is used on all posts, i've set the dimensions to 512x1024
