### ISSUE TITLE
The view or its master was not found or no view engine supports the searched locations.

### ISSUE THREAD

**Issue by abhilashca** [Shazwazza/Articulate#204]
Hi,

We have an Umbraco v7.2.4 which uses Articulate for blogging platform. When I try to preview a blog post, it is showing error - "_The view '~/App_Plugins/Articulate/Themes//Views/Post.cshtml' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/App_Plugins/Articulate/Themes//Views/Post.cshtml_". From the error message, it looks like theme name is missing which inturn breaks the entire path and causing the error.

Below is the screenshot of the error:

![ublog_error](https://cloud.githubusercontent.com/assets/12084395/21350379/085bd4ae-c6dd-11e6-91d4-7022a105a63e.png)

However, I could publish the blog post directly and can view the same while navigating to my website. The issue is with previewing only.

Any idea why the path breaks in between?
Any help will be appreciated.
Thanks.

**Comment by simonech** [comment]
It looks like you don't have a theme set. But if you see it on the published site then obviously is not the problem.

**Comment by abhilashca** [comment]
Thanks for the quick reply. The long story is I am an Umbraco newbie and working on the Umbraco version which was customized by some other vendor. And I am not sure which piece had gone wrong here.

Can you please suggest some areas where I could sneak to look for potential issues? I checked Umbraco back-office but couldn't find any section related to Themes.

**Comment by simonech** [comment]
Themes are properties in the articulate node

**Comment by abhilashca** [comment]
Thanks for the reply. I couldn't find the theme property in my customized version. Looks like somewhere it is hard-coded and something had gone wrong. I'll take further look from here.
Thanks for the help.

**Comment by simonech** [comment]
@abhilashca no problem. Let me know if you need more help
