### ISSUE TITLE
Nest URLs under Blog Root

### ISSUE THREAD

**Issue by kcappieg** [Shazwazza/Articulate#205]
I use this plugin as an add-on for a site which is not primarily a blog. Having the URL for the blog root be `/blog` is great: it does what I want it to. However, I'd like posts' links to be nested under the URL.

For instance: `/blog/archive/my-blog-post`

Instead, for some reason the url is `/archive/my-blog-post`

Can this be addressed?

Also, if any commenters know where I can change the URL in the Articulate codebase in the meantime, that would be great. Everything I've read about Umbraco indicates that the URL should be structured based on the nodes' tree structure, but that doesn't seem to be the case with Articulate!

**Comment by simonech** [comment]
Just put the archive node in the root of the site.
No need to change any line of code

**Comment by kcappieg** [comment]
Putting the archive node in the site root wouldn't solve the problem: I *want* the archive to be nested under the blog node and have the posts' urls structured as `/blog/archive/my-blog-post/`.

I tried moving it just in case I misunderstood, but it didn't do anything. All my posts are still at `/archive/my-blog-post`.

Is it intended behavior that the URLs are structured this way? If so, then it had to be set somewhere, right?

(Thanks for responding so quick, by the way.)

**Comment by kcappieg** [comment]
I'm sorry, I was misunderstanding! I figured out what you meant. (Put the Articulate Node under my root home page.)

Thanks again!

**Comment by simonech** [comment]
Sorry, I misunderstood :)

Articulate has virtual routes that do not match directly to Umbraco nodes.

I'm out now, cannot visualise the problem.
So you have a tree like this?

- root
     |- blog
            |- archive 

Simone

**Comment by simonech** [comment]
Glad it helped :)
