### ISSUE TITLE
Categories placeholder text

### ISSUE THREAD

**Issue by mbuchok** [Shazwazza/Articulate#209]
Extremely minor, but the placeholder text for 'categories' is mentioning tags

![categories](https://cloud.githubusercontent.com/assets/5552600/22174395/93a3c86e-dfab-11e6-93d3-a1601f258a99.PNG)

**Comment by Shazwazza** [comment]
This is part of umbraco not articulate. You'd need to open a feature request to umbraco to be able to modify that text via a pre value
