### ISSUE TITLE
Tags and Categories URL not working with Arabic language

### ISSUE THREAD

**Issue by developeryounis** [Shazwazza/Articulate#211]
**Dear Shannon**

i have a problem using tags and categories with Arabic languages it's recording into db as "??? ????? ??????" and i got error when use tag or category URL.

i'm using **umbraco version 7.5.3** and **Articulate version 2.0.5**

i put globalization element to web.config and put accept-charset="utf-8" attribute to umbraco form and i got the same problem
```
web.config globalization element
<globalization  fileEncoding="utf-8"  requestEncoding="utf-8" responseEncoding="utf-8" enableBestFitResponseEncoding="true" responseHeaderEncoding="utf-8" culture="ar-EG" uiCulture="ar-EG" />
```

**Comment by Shazwazza** [comment]
Hi, I've tested my installation with arabic characters and it seems to work fine. I would suggest that the issue is probably the culture that you are using in your SQL database. Have a look here: http://stackoverflow.com/questions/3560173/store-arabic-in-sql-database

**Comment by developeryounis** [comment]
**Dear Shannon**

thank you for support and finally i find the solve of the problem after upgrade from version 7.5.3 to 7.5.8

**Comment by Shazwazza** [comment]
great news!
