### ISSUE TITLE
Issue calling Partial views into homepage

### ISSUE THREAD

**Issue by bobi33** [Shazwazza/Articulate#218]
Hi,

Appears to be an issue pulling a partial view into my home page? I just wanted to reference:

`@Html.ThemedPartial(Model, "Latest")` into my homepage, which would show a list of recent blog posts (like a widget). I called the necessary Models, etc. through `@inherits Umbraco.Web.Mvc.UmbracoViewPage<Articulate.Models.PostModel>`, but this is giving me the following error:

> CS0426: The type name 'Models' does not exist in the type 'Umbraco.Web.PublishedContentModels.Articulate'

I alos tried:

`@Html.Partial("/Views/Latest.cshtml", new Articulate.Models.ListModel(Umbraco.Content(1066)))`

(with no luck),

and: 

`@Html.Partial("~/App_Plugins/Articulate/Themes/MyTheme/Views/Partials/Latest.cshtml", Model)`

I get the following error: 

>     Umbraco.Web.Mvc.ModelBindingException: Cannot bind source content type Umbraco.Web.PublishedContentModels.Index to model type Articulate.Models.IMasterModel.

**Comment by bobi33** [comment]
I'm basically trying to get my Latest.cshtml partial view inside my homepage footer by referencing this:
`@Html.ThemedPartial(Model, "Latest")`

My partial view includes:

`@using Articulate`
`@using Articulate.Models`
`@inherits UmbracoViewPage<Articulate.Models.IMasterModel>`

**Comment by bobi33** [comment]
Figured it out.

**Comment by Abhith** [comment]
@bobi33 Will you share how you managed to make it work?
I'm having a similar situation where I wanted to get recent posts in a partial view of custom page.

**Comment by gavinfaux** [comment]
Views outside of the folder App_Plugins\Articulate\Themes\YOURTHEME\Views won't be a Model of type Articulate.Models.IMasterModel; you need resolve this yourself via standard MVC & Articulate API & your own code 

E.g. example macro used with grid editor to list posts using a shared themed partial:

    @using Articulate
    @using Articulate.Models
    @using Umbraco.Web.Macros
    @inherits PartialViewMacroPage
    @{
        // snipped code, won't compile
        var tagsToLookupList = Model.MacroParameters["tags"] != null ? Model.MacroParameters["tags"].ToString().ToLower(CultureInfo.CurrentUICulture).Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries) : new string[0];

        List<PostModel> collection = ApplicationContext.GetBlogPostsByTag(Umbraco, tagsToLookupList).ToList();
        var master = Umbraco.GetArticulateRoot();
        foreach (var item in collection)
        {
            @Html.ThemedPartial(master, "ListItem", item)
        }
        // TODO: custom PagerModel required if paging required (will need to implement extension)
        // @Html.ThemedPartial(master, "Pager", collection.Pages)
    }

    public static class ArticulateExtensions
    {
        // snipped code, won't compile
        public static IMasterModel GetArticulateRoot(this UmbracoHelper helper)
        {
            //TODO: This assumes only 1 root articulate node in content tree
            var content = helper.TypedContentSingleAtXPath("//Articulate").Children<ArticulateArchive>();
            return new MasterModel(content.FirstOrDefault());
        }
        public static IEnumerable<PostModel> GetBlogPostsByTag(this ApplicationContext appContext, UmbracoHelper helper, IEnumerable<string> tagsToLookupList)
        {
            // can't use C#7 local/nested functions (requires VS2017) so using private instead
    #if DEBUG
            return helper.BlogPostsByTag(tagsToLookupList);
    #else // tag queries hit db - cache this result for a short amount of time
            var toLookupList = tagsToLookupList.OrderBy(s => s.ToLower(CultureInfo.CurrentCulture)).ToArray();
            return (IEnumerable<PostModel>) appContext.ApplicationCache.RuntimeCache.GetCacheItem(string.Concat(typeof(ArticulateExtensions).Name, "GetBlogPostsByTag", string.Join(",", toLookupList)), () => helper.BlogPostsByTag(toLookupList), Config.For.RunTimeCacheTimeout);
    #endif
        }
