### ISSUE TITLE
Url Name Customization Issue + Doc Type

### ISSUE THREAD

**Issue by bobi33** [Shazwazza/Articulate#219]
It looks like if you install articulate to an existing site (i.e. a Homepage), you will have a subfolder in the homepage with this structure:

-Homepage
      - Articulate
         -->Archive
         -->Authors

 If you were to create a breadcrumb to an article it would appear as so: www.sitename.com/articulate/archive/"article-name"; however, if you want to customize the url to remove the "articles" directory or "archive", it's not possible with the way the doc type is set up. 

Am I correct, or is there a way around this?

**Comment by Shazwazza** [comment]
This sort of relates to this https://github.com/Shazwazza/Articulate/issues/213

but since you are in charge of creating your own breadcrumb then just skip the 'archive' (ArticulateArchive doc type)
