### ISSUE TITLE
Umbraco application won't run/install since project update to Umbraco 7.5.11

### ISSUE THREAD

**Issue by skidmow** [Shazwazza/Articulate#221]
It appears that the config/imageprocessor files are missing, therefore you can't run the web project from a clone of the Articulate repository. You need to add those missing files manually or it won't run/install Umbraco.

**Comment by Shazwazza** [comment]
I thought the Nuget restore would add those files on a fresh checkout of the source when this process is followed to get started? https://github.com/Shazwazza/Articulate#contributing

**Comment by skidmow** [comment]
The nuget restore didn't add them for me. It adds everything else and the project will build fine, but it won't run.

On 20 Mar 2017 00:23, Shannon Deminick <notifications@github.com> wrote:

I thought the Nuget restore would add those files on a fresh checkout of the source when this process is followed to get started? https://github.com/Shazwazza/Articulate#contributing

**Comment by Shazwazza** [comment]
I've pushed those files now
