### ISSUE TITLE
Add Articulate property types to lucene?

### ISSUE THREAD

**Issue by bobi33** [Shazwazza/Articulate#222]
Is there a way to add the Articulate property types to lucene? I'm trying to search the articulate node (which is not the parent node), but it's not being picked up in my searches.

**Comment by Shazwazza** [comment]
You'll need to provide more information about what you are actually doing and what results you are expecting. (i.e. steps to replicate, etc...()

**Comment by bobi33** [comment]
My website is set up like so:

Homepage
-About
-FAQ
-Articulate Blog

Articulate blog is not the root node.

I am using ezSearch to search for content (property aliases) on the whole site. It works except it doesn't search the blog posts from articulate, or articulate generally.

Is there a way to add articulate property aliases to examine (but I would assume they are already there)?

On Mar 19, 2017, at 22:31, Shannon Deminick <notifications@github.com<mailto:notifications@github.com>> wrote:


You'll need to provide more information about what you are actually doing and what results you are expecting. (i.e. steps to replicate, etc...()

**Comment by Shazwazza** [comment]
Articualate doesn't do anything specifically with indexes. Articulate is just using Umbraco data so it will be indexed just like any other umbraco data so I'm not really sure why you are experiencing this problem. I'd suggest rebuilding your indexes and checking with Luke to see what is actually going into your indexes.

**Comment by bobi33** [comment]
Thanks for the response Shannon. I will rebuild the indexes again and let you know if that fixes things. I assumed that by adding the Articulate property aliases: blogDescription, blogTitle, blogPost, tags, tagsPageName, tagsUrlName, categories, categoriesPageName, categoriesUrlName, and excerpt to the ezSearch macro it would pick up the blog posts just like any other property type in Umbraco. Too bad umbraco doesn't have some type of function to call all property aliases.

`@Umbraco.RenderMacro("ezSearch", new {rootContentNodeId="1052", rootMediaNodeId="", indexType="BOTH", searchFields="nodeName, metaTitle, metaDescription, metaKeywords, bodyText, blogDescription, blogTitle, blogPost, tags, tagsPageName, tagsUrlName, categories, categoriesPageName, categoriesUrlName, excerpt", previewFields="nodeName, metaTitle, metaDescription, metaKeywords, bodyText, blogDescription, blogTitle, blogPost, tags, tagsPageName, tagsUrlName, categories, categoriesPageName, categoriesUrlName, excerpt", previewLength="381", pageSize="10", hideFromSearchField="", searchFormLocation="NONE"})`
