### ISSUE TITLE
How to remove comma from  Url.ArticulateTagUrl

### ISSUE THREAD

**Issue by bobi33** [Shazwazza/Articulate#223]
How would you remove the comma (,) from the tags listed in the following list? The tags currently show up as: tag1, tag2, tag3, etc. I am trying to get them to not be separated by the comma, similar to how it is with TagCloud.
`<li>
                            <i class="fa fa-tags"></i> @Html.ListTags(Model,
                                                    @<a href="@Url.ArticulateTagUrl(Model, @item)">@item</a>)
                        </li>`

**Comment by ProNotion** [comment]
ListTags has a delimeter parameter, have you tried setting it to `string.Empty`?

    <li> <i class="fa fa-tags"></i> @Html.ListTags(Model, @<a href="@Url.ArticulateTagUrl(Model, @item)">@item</a>, delimiter: string.Empty) </li>
