### ISSUE TITLE
How to add pager to recent view

### ISSUE THREAD

**Issue by bobi33** [Shazwazza/Articulate#224]
How can you add pager.cshtml to the recent.cshtml view, so as to make it like a list of all posts?

I have the pager working with search results, but I can't get it to work with recent.cshtml. If you have 30 results, then say, after 10, then you'd have 3 pages.

Essentially I am looking to make my Recent.cshtml page to show all blog posts with the addition of the pager, and be the default page that users land on when they go to the blog link.

My List.cshtml looks like this:

>     @using Articulate
    @using Articulate.Models
    @using ClientDependency.Core.Mvc
    @using Umbraco.Core
    @using Umbraco.Web
    @using Umbraco.Web.Models
    @inherits UmbracoViewPage<ListModel>
    @{
    Layout = "Master.cshtml";

    }

    @*Render different content if it's the homepage*@
    @if (Model.DocumentTypeAlias == "ArticulateArchive")
    {

    @Html.ThemedPartial(Model, "Recent")

    }
    else
    {

    if (!Model.Children.Any())
    {

        if (!Request.QueryString["term"].IsNullOrWhiteSpace())
        {

            
            <div class="col-md-9 md-margin-bottom-40">
                
                <div class="blog margin-bottom-40">
                    @*<h2>Search Results</h2><br /><br />*@

                    <p class="lead">No articles found for search term <strong>@Request.QueryString["term"]</strong>.</p>

                </div>
                
                <hr>

            </div>
            
        }

    }
    else
    {
        if (Request.QueryString["term"] == "")
        {

            
            <div class="col-md-9 md-margin-bottom-40">
                
                <div class="blog margin-bottom-40">
                    @*<h2>Search Results</h2><br /><br />*@

                    <p class="lead">Please enter search criteria.</p>

                </div>
                
                <hr>

            </div>
            
        }
        else
        {
            
            <div class="col-md-9 md-margin-bottom-40">
                
                    @{     
                        

                    var categoryPath = "/articles/categories/";
                    var tagPath = "/articles/tags/";

                   
                    }

                    @if (Model.Pages.TotalPages > 1)
                    {

                        if (!Request.QueryString["term"].IsNullOrWhiteSpace())
                        {
                            <p class="lead">Your search for <strong>@Request.QueryString["term"]</strong> matched <strong>@Model.Pages.TotalPages</strong> results.</p>
                            <p class="lead">Showing results <strong>@Model.Pages.TotalPages</strong> to <strong>@Model.Pages.TotalPages</strong>.</p>
                        }

                        else if (Request.Path.Contains(categoryPath))
                        {
                            <p class="lead">Your search for <strong>@Request.Path.Remove(0, 21)</strong> matched <strong>@Model.Pages.TotalPages</strong> results.</p>
                            <p class="lead">Showing results <strong>@Model.Pages.TotalPages</strong> to <strong>@Model.Pages.TotalPages</strong>.</p>
                        }

                        else if (Request.Path.Contains(tagPath))
                        {
                            <p class="lead">Your search for <strong>@Request.Path.Remove(0, 15)</strong> matched <strong>@Model.Pages.TotalPages</strong> results.</p>
                            <p class="lead">Showing results <strong>@Model.Pages.TotalPages</strong> to <strong>@Model.Pages.TotalPages</strong>.</p>
                        }

                    }
                    else
                    {
                        if (!Request.QueryString["term"].IsNullOrWhiteSpace())
                        {
                            <p class="lead">Your search for <strong>@Request.QueryString["term"]</strong> matched <strong>@Model.Pages.TotalPages</strong> result.</p>
                            <p class="lead">Showing results <strong>@Model.Pages.TotalPages</strong> to <strong>@Model.Pages.TotalPages</strong>.</p>
                        }

                        else if (Request.Path.Contains(categoryPath))
                        {
                            <p class="lead">Your search for <strong>@Request.Path.Remove(0, 21)</strong> matched <strong>@Model.Pages.TotalPages</strong> result.</p>
                            <p class="lead">Showing results <strong>@Model.Pages.TotalPages</strong> to <strong>@Model.Pages.TotalPages</strong>.</p>
                        }

                        else if (Request.Path.Contains(tagPath))
                        {
                            <p class="lead">Your search for <strong>@Request.Path.Remove(0, 15)</strong> matched <strong>@Model.Pages.TotalPages</strong> result.</p>
                            <p class="lead">Showing results <strong>@Model.Pages.TotalPages</strong> to <strong>@Model.Pages.TotalPages</strong>.</p>
                        }
                    }

                    @foreach (var post in Model.Children<PostModel>
                                                ())
                    {
                        @Html.ThemedPartial(Model, "PostSearch", post, new ViewDataDictionary { { "IsListView", true } })<br /><br />
                    }

               

                    @Html.ThemedPartial(Model, "Pager", Model.Pages)

               

            </div>
            

                                }

                            }

                        }

**Comment by NoelleMe** [comment]
Is there any update on this? I'm looking to do the same thing...

**Comment by Shazwazza** [comment]
If you follow the code, you can see what is happening:

Recent.cshtml is here https://github.com/Shazwazza/Articulate/blob/master/src/Articulate.Web/App_Plugins/Articulate/Themes/Shazwazza/Views/Partials/Recent.cshtml, it uses the method `Umbraco.GetRecentPosts` to get the 5 latest posts, that method is here:  https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/UmbracoHelperExtensions.cs#L144, but this method also has an overload for paging: https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/UmbracoHelperExtensions.cs#L166
which you could use. 

You'd have to track the page number in query strings and update your Recent.cshtml to use those query strings to do the paging. 

You could then do the paging with Pager.cshtml (see https://github.com/Shazwazza/Articulate/blob/master/src/Articulate.Web/App_Plugins/Articulate/Themes/Shazwazza/Views/Partials/Pager.cshtml) which gets given a model of type `Articulate.Models.PagerModel` (see https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/Models/PagerModel.cs) so you'd have to create this model to pass to the pager with the correct data/urls including the query strings you wish to use.
