### ISSUE TITLE
MSBuild Issues Due to Out Parameters

### ISSUE THREAD

**Issue by ProNotion** [Shazwazza/Articulate#229]
For some reason when I run the Build script I get errors like this:

> D:\Repositories\Umbraco\Articulate\src\Articulate\Articulate.csproj" (default target) (3) ->
>        (CoreCompile target) ->
>          Controls\Installer.cs(18,50): error CS1525: Invalid expression term 'bool' [D:\Repositories\Umbraco\
>        Articulate\src\Articulate\Articulate.csproj]

The issue is with lines like this:

`var root = dataInstaller.Execute(out bool packageInstalled);`

If I amend it to:

```
bool packageInstaller;
var root = dataInstaller.Execute(out packageInstalled);
```

...it then works fine. I'm no real expert at the moment when it comes to MSBuild and it builds fine in Visual Studio so not sure what the issue is?

**Comment by gavinfaux** [comment]
There are C#7 language features now being used which requires MS Build 15 (VS 2017). 

My current workaround is to build by changing line 19 of build.ps1 to use MS Build 15:

`$MSBuild = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe";`

And by copying the WebApplications build targets folder from `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\` to the `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\`
