### ISSUE TITLE
Tags and Categories disappear for already published posts

### ISSUE THREAD

**Issue by bobi33** [Shazwazza/Articulate#230]
Hi,

Tags and Categories disappear for already published posts while making changes to the Articulate (i.e. moving Articulate into another node, or making it a root node).

**Comment by Shazwazza** [comment]
Is this due to the small amount of caching that occurs for categories/tags? Does it still do this if you have compilation debug="true in your web.config ?

**Comment by philius44** [comment]
just seen that my issue post https://github.com/Shazwazza/Articulate/issues/268 is a duplicate of this. Yes, I have debug=true in my web.config and the issue is still there.

**Comment by Shazwazza** [comment]
closing as duplicate of #268
