### ISSUE TITLE
Tags and Categories dont work in Umbraco 7.6

### ISSUE THREAD

**Issue by JohnBergman** [Shazwazza/Articulate#233]
This is because the model returned is now an IEnumerable<string> or string[], rather than a string.  There appears to be code (at least) in postmodel that treats the data from Umbraco as a string array and parses it out.  Not sure if this is an ideal fix, but changing the two properties to be like this appears to have it working.

`        public IEnumerable<string> Tags
        {
            get
            {
                return this.GetPropertyValue<IEnumerable<string>>("tags");
            }
        }

        public IEnumerable<string> Categories
        {
            get
            {
              return this.GetPropertyValue<IEnumerable<string>>("categories");
            }
        }
`

**Comment by Shazwazza** [comment]
You need to disable the new built in property value converters until i make a new version that supports the new ones

http://issues.umbraco.org/issue/U4-7318

see https://github.com/Shazwazza/Articulate/issues/231#issuecomment-299101632

**Comment by JohnBergman** [comment]
Ok.  Any chance you are going to update it to use the new ModelBuilder support in 7.6, it is much better than what was in the 7.5 implementation :-).

**Comment by Shazwazza** [comment]
I'll be updating this project to support a min of 7.6 but ModelsBuilder won't be necessary, articulate comes with it's own strongly typed models. It will use the new property value converters though if they are turned on.

**Comment by abhilashca** [comment]
@Shazwazza Does this means I can use Articulate in v7.6 by disabling the new built-in property value converters. If so, when you added necessary support in upcoming Articulate version, I'll have to fall back to original built-in property value converters, correct? Do you anticipate any blockers or issues, if I use that approach?

Thanks.

**Comment by Shazwazza** [comment]
@abhilashca Yes, that is what it means. In Articulate 3 it will work with them enabled or disabled, it performs a check for this. You can always try Articulate 3 now, it's in beta https://github.com/Shazwazza/Articulate/releases/tag/v3.0.0-beta1

**Comment by biapar** [comment]
@JohnBergman 

I solved in this mode:

```
var tagList = item.GetPropertyValue<string[]>("department");  
@foreach (var itemTag in tagList)
   {
      <span>
     @itemTag
       </span> 
        }
```
