### ISSUE TITLE
Cannot run Articulate.Web

### ISSUE THREAD

**Issue by LeinadDC** [Shazwazza/Articulate#234]
I'm trying to run Articulate.Web in order to add a property I need in the posts in order to implement a feature I want.

At first, I got Null Exception with no other information. Running it a second time, with no changes made got me this other error.

```

[Exception: The Xml cache is corrupt. Use the Health Check data integrity dashboard to fix it.]
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetXml(UmbracoContext umbracoContext, Boolean preview) +80
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.HasContent(UmbracoContext umbracoContext, Boolean preview) +14
   Umbraco.Web.PublishedCache.ContextualPublishedCache`1.HasContent(Boolean preview) +35
   Umbraco.Web.UmbracoModule.EnsureHasContent(UmbracoContext context, HttpContextBase httpContext) +41
   Umbraco.Web.UmbracoModule.EnsureUmbracoRoutablePage(UmbracoContext context, HttpContextBase httpContext) +112
   Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext) +211
   Umbraco.Web.UmbracoModule.<Init>b__8(Object sender, EventArgs e) +80
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
```

**Comment by Shazwazza** [comment]
Don't really think this is a problem with Articulate, sounds like a problem with Umbraco or your umbraco install.

Did you go check the health check dashboard like the error message is saying?

**Comment by LeinadDC** [comment]
Yeah. Everything says "Ok".

Only happening when running it from solution though. I have an installed Articulate on Umbraco and it's working just fine.

**Comment by Shazwazza** [comment]
Ah i see I didn't realize this was an issue with the solution (need to specify those sorts of details in bug reports otherwise I have no idea)

Is this with a clean checkout and then following these steps: https://github.com/Shazwazza/Articulate#contributing ?

**Comment by nvisage-gf** [comment]
It's due to the installer not running if web.config has a value for the `umbracoConfigurationStatus` setting, instead it tries to talk to DB which is not there yet. Removing value allows installer to run.

**Comment by nvisage-gf** [comment]
Q: Should the Web project have Articulate usable for developing (package installed) after clean checkout and build, or does the zip have to be installed via Package Manager? 

I'm sure this was working over the weekend as made some submissions; but seem to be missing a step now?

**Comment by simonech** [comment]
The webconfig in the repo should be a clean version that installs without issues. If it is not, then a PR or a commit screwed it up :)

As for the rest, the wiki explains it. If I remember correctly, you need to install the package once via zip or even with the one online and then each build will update the files.
