### ISSUE TITLE
Minimum Umbraco version of 7.6

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Articulate#243]

**Comment by Shazwazza** [comment]
The first step for this is done - now it's just a matter of updating things with the property value converters

**Comment by ErdoganMutlu** [comment]
I would like to know when are you planning to release a new version.

**Comment by Shazwazza** [comment]
As soon as it's ready and i have time to finish this version, i would like to release in the next 2 weeks but who knows if i find the time.

**Comment by steiniofur** [comment]
ETA?
