### ISSUE TITLE
Unable to publish Articulate posts on 7.6.1

### ISSUE THREAD

**Issue by KrisJanssen** [Shazwazza/Articulate#244]
Hi,

I got hit by an odd issue. I upgraded a 7.4.x to 7.6.1 and everything went smoothly.

I disabled the new property value converters in umbracoSettings.config to be safe.

When I now try to publish posts in Articulate I get:

    System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

I originally posted on the issue at [our.umbraco.org](https://our.umbraco.org/forum/using-umbraco-and-getting-started/85733-articulate-unable-to-publish-posts-after-upgrade-to-761)

So far, I have been unable to determine if this is specific to my site or more general.

**Comment by Shazwazza** [comment]
I'll close this issue as a check was added in articulate to check for the existence of these properties some time ago.
