### ISSUE TITLE
Update umbraco+articulate to latest release of articulate?

### ISSUE THREAD

**Issue by dyardyGIT** [Shazwazza/Articulate#253]
I have an earlier version of articulate and I don't think the export existed in this release 1.x. I am working on trying to upgrade the articular version, however not sure how to do this ..any ideas? (i have the umbraco+articulate open in vs.net) i have downloaded articulate but not sure how to merge/update these.

ideas

**Comment by simonech** [comment]
Answered in #252 
Please close the issue
