### ISSUE TITLE
Set Articulate Excerpt field to be used as meta description or create separate meta description field

### ISSUE THREAD

**Issue by garrettatx** [Shazwazza/Articulate#262]
I'm an [SEO freelancer](https://www.garrettdigital.com/) reviewing Articulate on behalf of a client. Right now one of the major faults is that a unique [meta description](https://moz.com/learn/seo/meta-description) doesn't get assigned to each post and there isn't a place to enter one. The excerpt field would be better than nothing, though it might exceed the 160 character limit for meta descriptions. This just means anything after the initial 160 characters would get cut off.

**Comment by Shazwazza** [comment]
In the upcoming v3 there are more SEO type fields, however, since this is just using Umbraco feel free to add any fields that you want to blog posts. You are in 100% control, if you want extra fields, add them, if you want to render them in the header, the markup is up to you :)

**Comment by simonech** [comment]
I think specific request is already done in v3 issue #171

**Comment by garrettatx** [comment]
Ah, thanks for finding and pointing that out. This is a critical issue for
SEO and improving the visibility of blog posts in search engines.

**Comment by simonech** [comment]
It would be awesome if you could have a look at v3 and see if anything else could be improved there.
We added meta tags from post's tags, and added also social media tags for Twitter cards and fb graph
