### ISSUE TITLE
Tags and Categories sometimes include /blog url path

### ISSUE THREAD

**Issue by GeorgDangl** [Shazwazza/Articulate#264]
I noticed a weird issue with my blog:
I've set up Articulate as my root node, so that my posts are found under `/archive`, tags under `/tags` and categories at `/categories`.

I noticed that when I do a fresh deploy of the site via WebDeploy, tags and categories introduce a `/blog` url, e.g. my `dotnet` tags link points to `/blog/tags/dotnet` instead of `/tags/dotnet`. I can solve this by republishing the entire blog.

Surprisingly, when I go to the `/blog` site, e.g. `https://example.com/blog` I see the start page. This also works for one of my custom pages (but not for another one...). I can go to `/blog/about` and get the same result as for `/about`. This stops working after doing the republish.

A solution-wide search doesn't turn anything up for me where this could be coming from. Do you have any ideas?

**Comment by GeorgDangl** [comment]
This rewrite rule takes care of that:

```xml
<rule name="Rewrite blog path" stopProcessing="true">
  <match url="^blog/(.*)"/>
  <action type="Redirect" url="{R:1}"/>
</rule>
```

**Comment by Shazwazza** [comment]
Sorry for the delay on responding here. I'd have to figure out how to replicate the issue locally to determine what is going on, it is definitely something to do with creating the tags/category routes. What articulate version are you using that has this issue?

**Comment by GeorgDangl** [comment]
I'm still on version 3.0.1 of Articulate.

However, I'm not sure when that behaviour first appeared. I noticed it because of 404 errors via the Google Webmaster Dashboard. There's not a lot in my commit history that could point to what's wrong. Two months earlier, I upgraded from Umbraco 7.5.8 to 7.6.0.

I'm using a custom theme, so I have built this in to prevent invalid links:

    @*There has been an issue with articulate where, when the page was visited via https://blog.dangl.me/blog, the "/blog"  
    path was included in the links and caused 404s*@ 
    <li><a href="@Url.ArticulateRootUrl(Model).Replace("/blog", string.Empty)">@Model.BlogTitle</a></li> 
    <li><a href="@Url.ArticulateCategoriesUrl(Model).Replace("/blog", string.Empty)">Categories</a></li> 
    <li><a href="@Url.ArticulateTagsUrl(Model).Replace("/blog", string.Empty)">Tags</a></li> 

But I have no idea how links to my `blog.dangl.me/blog` have been introduced. That's not an url I use and there should be no links to it from anywhere.  
I checked locally right now, the Articulate root node is called "Blog" and it's relative link is `/blog/`. When I visit it, the articulate links contain the `/blog/` part.

As far as I'm concerned, you can close this issue if it's not affecting anyone else. The rewrite rule is taking care of it.

**Comment by Shazwazza** [comment]
Going to close this issue, if there's a way to replicate let me know. I haven't heard the issue from others.
