### ISSUE TITLE
Installation error Value cannot be null - all versions 

### ISSUE THREAD

**Issue by janduch** [Shazwazza/Articulate#265]
Hello, I'm having following error when trying to install Articulate:

Value cannot be null.
Parameter name: virtualPath

Doesn't matter which version I'm trying to install, every time I'm getting this. 
Umbraco Version 7.3.1

Anyone came across this ?? 

Thanks

Jan

**Comment by janduch** [comment]
Done......... The error was caused by a space in my web.config in umbracoReservedUrls !!! For anyone who will come across this

**Comment by Shazwazza** [comment]
Thanks for reporting and glad you found the solution!
