### ISSUE TITLE
Articulate Markdown and Articulate Theme Picker DataTypes throw an Exception

### ISSUE THREAD

**Issue by philius44** [Shazwazza/Articulate#267]
After installation of Articulate first things were fine, but after pushing that installation to our git repository and retrieving it in a new repo copy, Articulate is broke in the sense that 2 Articulate DataTypes cannot be resolved and are leading to other errors. Other Articulate DataTypes work. Umbraco Backend is the same in both cases.

Could someone please point us in the right direction?

Errors from the Umbraco Backend: https://pastebin.com/YtTVWx70
Umbraco Version: 7.5.8

**Comment by Shazwazza** [comment]
This is something related to your environment and how you are deploying, not Articulate.

You can see in the stack trace:

```
 System.InvalidOperationException: Could not find property editor with alias Articulate.MarkdownEditor
```

which means you haven't deployed the Articulate DLLs and/or the App_Plugins/Articulate folder to the destination since it cannot find this property editor

**Comment by philius44** [comment]
Thanks, the dll's were missing.
