### ISSUE TITLE
Don't strip first image from markdown when assigning image to the image property

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Articulate#269]
Based on this PR: #261

the way i've done it is to strip the first image from the MD so that we don't have 2x images rendering, but this might not be what people want so i'll need to revert that behavior and then add docs based on the responses in that PR.

**Comment by stokesy43** [comment]
Not sure, I can think of use cases for both.

**Comment by Shazwazza** [comment]
will close this for now then and we'll keep the stripped image from getting into the markdown
