### ISSUE TITLE
Render list of posts for time period from URL segments 

### ISSUE THREAD

**Issue by warrenbuckley** [Shazwazza/Articulate#271]
If I use the option to prefix the URL of the blog post with the date such as http://localhost:6200/archive/2017/07/01/my-custom-url

So if I hack the URL and remove it to
http://localhost:6200/archive/2017 I would expect a list of all posts that are posted in the same time range

Again if I do the same with any part of the URL such as month & the day too, in case multiple posts posted on a single day.

Alternatively this could redirect back up to the home or archive node

**Comment by warrenbuckley** [comment]
Have CC'd you @simonech as I see you created this feature and may have some feedback/input on this

**Comment by Shazwazza** [comment]
@warrenbuckley  that is a totally brand new feature request and would take quite a bit of work actually. If we did that it would need to be supported for normal URLs and for DateTime URLs, we wouldn't want to only enable this specifically for when DateTime URLs are turned on.

Redirecting would be far easier for now.

**Comment by warrenbuckley** [comment]
Yeh after a quick skim last night at how is been implemented then yep realize now its fair bit of work, like you say a redirect would be best.
