### ISSUE TITLE
Uninstall package removes CookComputing.XmlRpcV2.dll

### ISSUE THREAD

**Issue by easyveazie** [Shazwazza/Articulate#273]
I am testing out Articulate and wanted to reinstall it to start with clean files. I uninstalled it and it removed CookComputing.XmlRpcV2.dll, which is appears to be required by Umbraco 7.6.6

Could not load all types from "umbraco, Version=1.0.6456.19237, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileNotFoundException: Could not load file or assembly 'CookComputing.XmlRpcV2, Version=2.5.0.0, Culture=neutral, PublicKeyToken=a7d6e17aa302004d' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'CookComputing.XmlRpcV2, Version=2.5.0.0, Culture=neutral, PublicKeyToken=a7d6e17aa302004d' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'CookComputing.XmlRpcV2, Version=2.5.0.0, Culture=neutral, PublicKeyToken=a7d6e17aa302004d' or one of its dependencies. The system cannot find the file specified.

**Comment by Shazwazza** [comment]
That's unfortunate but not a ton i can do. The reason is because Umbraco 7.7 doesn't ship with this dependency so it's required to be a dependency of this nuget package too but if you installed Umbraco via Nuget surely it wouldn't remove that because umbraco 7.6 has that listed as it's own dependency.

Did you install Umbraco via Nuget?

**Comment by easyveazie** [comment]
Yes I did.

**Comment by Shazwazza** [comment]
only thing you can do is re-install either package with Nuget to get the DLL back. This is really a nuget issue that i don't have control over.
