### ISSUE TITLE
/backoffice/UmbracoApi/Content/GetChildren returns no elements after upgrade to 3.0.1 via nuget

### ISSUE THREAD

**Issue by GeorgDangl** [Shazwazza/Articulate#274]
After upgrading both Umbraco and Articulate to 7.7.1 / 3.0.1, my back office is no longer displaying child entries for any list content. In my case, this is all posts below the `Archive` node as well as the child elements of a custom element I have put below the root blog node. New items can be added, but still won't show up in the overview.

When loading elements in the backoffice via the url `/umbraco/backoffice/UmbracoApi/Content/GetChildren?id=1060&pageNumber=2&pageSize=10&orderBy=SortOrder&orderDirection=Ascending&orderBySystemField=true&filter=`, that's the response I get:

    )]}',
    {"pageNumber":2,"pageSize":10,"totalPages":5,"totalItems":43,"items":[]}

(I guess the first part is intentional for security issues)

The response gives the correct count of child items, but the `items` array is empty.

**Upgrade path**

I did have Articulate already installed, so I just removed the dll I had manually referenced and installed via nuget. The template files were updated.
I *think* the issue happened only after I clicked *install* in the Articulate dashboard, but I unfortunately didn't anticipate this error so I don't remember if I checked the content before clicking the install button.

**Still working**

* Content is displayed completely fine on the front end
* I can manually navigate to entries by pasting the url, e.g. `/umbraco/#/content/content/edit/1200`
* BlogMI export contains all the entries
* Database looks fine, but I'm not experienced with the Umbraco schema so I might be wrong

Any chance you could help me track this issues cause?

**Comment by Shazwazza** [comment]
This is the Core problem http://issues.umbraco.org/issue/U4-10437 with a work around posted
