### ISSUE TITLE
More documentation on Tags and Categories

### ISSUE THREAD

**Issue by blachawk** [Shazwazza/Articulate#276]
I am working through the current documentation on Articulate here on Github.  By any chance, would there be any additional resources online that show us how we can take full control / customization of categories and tags through Articulate? Perhaps examples or walk-throughs to maximize our efforts on this feature of the package?

**Comment by Shazwazza** [comment]
Articulate is built on Umbraco and tries to utilize as much from Umbraco as possible. Tags and Categories are based totally on Umbraco's Tag system. So that's entirely how it works. I think documentation for this stuff should be found on the Umbraco docs site
