### ISSUE TITLE
Nuget install does not work

### ISSUE THREAD

**Issue by hotelplan-poornima** [Shazwazza/Articulate#277]
Nuget install does not create the doc types. I am unsure whether this is the expected behaviour

**Comment by GeorgDangl** [comment]
You have to manually do it in the backoffice, via `Developer` -> `Articulate Management` -> `Installer`

**Comment by Shazwazza** [comment]
Yes that is expected. There is no way that Nuget can just install data into your Umbraco instance. Nuget doesn't know what Umbraco is and it doesn't have access to start a website or write to your database.
