### ISSUE TITLE
importing wordpress xml file

### ISSUE THREAD

**Issue by ShInoue** [Shazwazza/Articulate#278]
I am trying to import wordpress xml file by Articulate.
But it occurs an import error as shown below.

ERROR Articulate.Controllers.ArticulateBlogImportController - Unhandled controller exception occurred
System.FormatException: The supplied syndication resource has a content format of Rss, which does not match the expected content format of BlogML.
   at Argotic.Data.Adapters.SyndicationResourceAdapter.Fill(ISyndicationResource resource, SyndicationContentFormat format)

Please tell me what can I do.

**Comment by simonech** [comment]
Articulate only imports BlogML files, not the WRX wordpress format.

You can try using this tool https://github.com/Dillie-O/blogmigrator (I never tried it) to convert

**Comment by ShInoue** [comment]
Thank you.
I modified a lot manually after importing.
