### ISSUE TITLE
There are some build erros in Articurate 3.0.0.

### ISSUE THREAD

**Issue by ShInoue** [Shazwazza/Articulate#279]
While I am building latest Articurate 3.0.0, some errors occure like shown below.

CS1525    C:\Users\shing\Documents\Visual Studio 2015\Projects\Articulate-master\src\Articulate\UmbracoHelperExtensions.cs	252 IEnumerable<PostsByTagModel> GetResult()

.......

Is there any way to avoid them?

Please let me know.

**Comment by GeorgDangl** [comment]
There's a [local function](https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/UmbracoHelperExtensions.cs#L252-L285) defined and your Visual Studio version (`2015` I assume from your project location) doesn't support that. It's a C# 7 feature (language version 7, not framework) and requires Visual Studio 2017.

**Comment by ShInoue** [comment]
Hello Georg,

It was simply due to my lack of study.
Thank you very much.
