### ISSUE TITLE
Build Failed After Clone

### ISSUE THREAD

**Issue by venkateswararao** [Shazwazza/Articulate#284]
Hi Shazwazza,

I clone the Articulate and open  Articulate.sln  under Articulate-master\src and Articulate.Web setup as a started application and build the solution it through error build failed. I am using Visual studio 2015.

**Comment by simonech** [comment]
I think it uses some features of C# 6/7, so you need to VS 2017

**Comment by venkateswararao** [comment]
Thank you  simonech, I will update my VS and check
