### ISSUE TITLE
Articulate 3.0.1 installed on Umbraco 7.7.2 ---- Not working 

### ISSUE THREAD

**Issue by star2k279** [Shazwazza/Articulate#285]
hi,

I have been trying to Install Articulate 3.0.1 on Umbraco 7.7.2 but,
1. the installation was not successful and as soon as I clicked, the "Finish" button, it gave an error that , "\package\Installer.aspx" not found.

2. Also different document Types are showing exceptions when I select them in DocumentType section.

Is there anyway to fix these errors? OR this Articulate is simply not for Umbraco 7.7.2 at the moment?

**Comment by Shazwazza** [comment]
I've seen the comment on Our here: https://our.umbraco.org/projects/starter-kits/articulate/discussions/89842-articulate-301-installed-on-umbraco-772-not-working

> Sounds like an issue with your Umbraco installation. I've just done a clean install of 7.7.2 and installed Articulate and it worked without any issue.

**Comment by star2k279** [comment]
apologies to post duplicate issue. I was desperate for the answer because of short deadline.
