### ISSUE TITLE
Latest version of Umbraco

### ISSUE THREAD

**Issue by jaydcrowe1989** [Shazwazza/Articulate#289]
Will Articulate be fixed to work with the latest version of Umbraco?

**Comment by Shazwazza** [comment]
Can you please explain the issue you are having and what version exactly you are referring to? My own website is running the latest version of Umbraco and the latest version of Articulate and it's working just fine.

**Comment by jaydcrowe1989** [comment]
I managed to get it working thank you. It installed it into a different folder instead of the App_Plugins folder. I moved the Articulate folder to the correct place and it is now working. Do you know of an easy way to get the latest 3 blogs to display on my homepage?

**Comment by Shazwazza** [comment]
How did you install it? 

> It installed it into a different folder instead of the App_Plugins folder. 

This seems very odd!

(please keep separate questions to separate issues/posts)
