### ISSUE TITLE
Macro Partials don't work on virtual pages

### ISSUE THREAD

**Issue by jaandrews** [Shazwazza/Articulate#29]
I am encountering issues with using macro partials in articulate. When visiting category pages, the macro errors out. This happens even when the macro partial has nothing but the inherits statement at the top. It does work as expected with the non virtual pages though.

I've also found that this is not an issue with the old way of handling Macros (using MacroEngines).

I am using v 1.0.3. Does 1.0.4 address this issue? The project I'm using it for is nearing launch, so I'm reluctant to risk the upgrade.

**Comment by Shazwazza** [comment]
This is fixed in umbraco now in rev: https://github.com/umbraco/Umbraco-CMS/commit/73e9ff04e80df4bb1aac610c7b78ad394d0266cc
