### ISSUE TITLE
Search results paging consecutive page urls missing search term

### ISSUE THREAD

**Issue by Garetha01** [Shazwazza/Articulate#291]
When the search is made the first result page url is:
SiteURL/support/search?term=sales

the 'Next page' url is as follows:
SiteURL/support/search?p=2

obviously the 'Next Page' show's no results as its missing the search term (should be: SiteURL/support/search?term=sales&p=2)

Can you give me some indication as to what would cause this, and how I could fix it?

Umbraco version: 7.6.1
Articulate version: 3.0.1

**Comment by Garetha01** [comment]
Hi Shazwazza, I'm no coder (have managed to wrestle out a new theme and write some handy scripts in razor) but fixing this may be beyond my expertise :-) . I can however make changes to files if that is all that's required, but i guess it will be more involved than just adding in the search term reference to the consecutive urls.

**Comment by Garetha01** [comment]
awesome, I had seen the update and assumed it was included in the 3.0.1, now that the version number has updated it should be good.

**Comment by Garetha01** [comment]
Upgraded without a problem, issue resolved, thank you for your time and efforts. :-)

**Comment by Shazwazza** [comment]
Great :)
