### ISSUE TITLE
Render Macro

### ISSUE THREAD

**Issue by pradeep-vainc** [Shazwazza/Articulate#293]
Hello, 

I'm rendering this macro in the master page of the website @Umbraco.RenderMacro("Topnav") which works just fine. I've added the same code in the 'VAPOR' master to show website navigation but it's causing an error. Can you please advise on how to render the macros in articulate templates? 

Thank you.

**Comment by Shazwazza** [comment]
what is the error, version, umb version, steps to replicate, etc... ?

**Comment by pradeep-vainc** [comment]
Never mind. I figured it out.
