### ISSUE TITLE
Can Articulate doc types be modified while allowing for further updates?

### ISSUE THREAD

**Issue by WillRay** [Shazwazza/Articulate#296]
Our team is keen on changing the Markdown editor for the Articulate Markdown document type. (Primarily to support the triple backtick syntax for multi-line code and also syntax highlighting hints.)

Will changing Articulate's document types create risk when updating to new Articulate versions in the future?

**Comment by Shazwazza** [comment]
Yup sure! When new versions are out, the upgrade logic is to sync additional doc types and property types. IIRC it does not modify existing property types so i don't think your changes will get reverted or anything. 

I'm about 98% sure on this, i haven't tested myself so this is just based on what I'm pretty sure happens during the upgrade process both based on the articulate dashboard and umbraco's packaging logic. (you can test this if you install Articulate 3.0.1, modify a property type, then upgrade to 3.0.2)

**Comment by rbanks54** [comment]
Love how quick you responded! You're on 🔥 😁
