### ISSUE TITLE
Tag being wrongly encoded on Tags/Categories if name contains spares and using full hostname

### ISSUE THREAD

**Issue by syska** [Shazwazza/Articulate#299]
When `PostsByTagModel` is being instanciated, its done with the following for the URL.

masterModel.RootBlogNode.Url.EnsureEndsWith('/') + baseUrlName + "/" + tag.ToLowerInvariant()

If: 
```
masterModel.RootBlogNode.Url = "http://localtest.me"
baseUrlName = "categories"
tag = "tag name"
```
It will be `http://localtest.me/categories/tag name`

When it's then being encoded to: `http%3a/localtest-me/categories/tag%20name` because of "tag name" is not valid and fails in `Uri.TryCreate(urlPath, UriKind.Absolute, out result)` in the `SafeEncodeUrlSegments` ... 

Not really sure what's the best way to fix this ... and even more important ... not breaking anything other places ... 

Reading some of the other issues we need to handle so we can decode and use it for querying again if the user navigates to the url.

Please let me know if you need more information ... 

Running Articulate 3.0.2
Umbraco: 7.13.1

**Comment by syska** [comment]
https://github.com/Shazwazza/Articulate/pull/300

**Comment by Shazwazza** [comment]
aha! i think i see the issue, when you have multiple domains assigned it will set the `masterModel.RootBlogNode.Url` to an absolute URL, but that is not always the case ... like my tests i think. 

have verified that it works. Only thing now is to deal with tags with spaces at the model level and not in the view level else we need to put that duplicate logic in all views. 

I should get this all merged and closed soon hopefully

**Comment by Shazwazza** [comment]
In most views the url helper method `ArticulateTagUrl` should be used to render tags, i'll double check that is the case. It doesn't hyphenate, it just encodes it.

**Comment by syska** [comment]
Basically we need to make sure everything is working when: `useDomainPrefixes is true` and 

I have two sites, blog og personal site which uses the same umbraco and the reason why I have the adobe enabled. I then guess most people run with the above set to false :-)
