### ISSUE TITLE
Pager url issues in category pages when blog is not root

### ISSUE THREAD

**Issue by jaandrews** [Shazwazza/Articulate#30]
Some of the values in PagerModel are not set correctly inside virtual pages. In the case I'm running into, the blog is a child of the home page, with the url "/blog." When I visit one of the category pages Model.NextUrl and Model.PreviousUrl in the Pager partial both start with "/blog/blog."

**Comment by StevenWillett** [comment]
@jaandrews how did you manage to get the pager partial to include the numerical navigation links and include the actual links themselves to the respective pages?

I am struggling to identify the root Url for the blog to enable me to populate this using variables and then assigning them to the relevant links.

![image](https://cloud.githubusercontent.com/assets/10869028/6064509/650a836e-ad56-11e4-9c16-4021918ce15e.png)

I have created a topic on this here: https://our.umbraco.org/projects/starter-kits/articulate/discussions/61107-Articulate-Pager-on-listcshtml-view,-show-current-page-number-but-be-a-link-to-respective-page-of-article
