### ISSUE TITLE
Import Articulate v4

### ISSUE THREAD

**Issue by jimbacha** [Shazwazza/Articulate#309]
Trying to use the import, says the posts have been successfully imported. Then when I attempt to go to the content section I get the 'are you sure you want to leave message'. Is there something I'm missing? I don't see another submit button or finished button. Then when I goto the blog none of the posts were imported. Thank you in advance.

**Comment by Shazwazza** [comment]
articulate version? umbraco version? do you have an example of what you are importing that you can share?

**Comment by Shazwazza** [comment]
doh! sorry, i just noticed the title of the post. So articulate 4 and what umbraco version? and can you share a file that is failing?

**Comment by aztekweb** [comment]
I was able to duplicate this issue under the following conditions on a fresh install.

1) Move the ArticulateArchive  "Archive" node to the Recycle Bin
2) Create a new ArticulateArchive node "Posts"
3) Run the import

Posts are applied to the original ArticulateArchive  node found without checking if that node is in the Recycle Bin.

**Comment by Shazwazza** [comment]
@aztekweb thanks for the report that is helpful!

**Comment by Shazwazza** [comment]
@aztekweb just having a look now. Also FYI - if you want to change the "archive" URL name you don't have to delete the original and re-create with a new name, or even rename the node if you don't want, you can change the URL name on the Archive node using the "Umbraco Url Name" property there.

I'll update here when i can replicate and fix.

**Comment by Shazwazza** [comment]
Fixed in rev af811609762b1fb5574eb1c21baf4d220bf8c8f9 which now also supports when the doc types are configured for language variants.
