### ISSUE TITLE
Dependency for Umbraco 8 not working

### ISSUE THREAD

**Issue by lcichanowicz** [Shazwazza/Articulate#311]
I just inadvertently installed Articulate 4 on a new, clean Umbraco 7.14.0 site, in Visual Studio 2019. via the NuGet Package Managuer GUI.

Of course it broke the Umbraco instance.  I started over, and mindfully chose Articulate 3.0.2.

**Comment by Shazwazza** [comment]
Not sure how it would let you do that unless you haven't installed Umbraco via Nuget. You can see here the 4.0.0 Nuget package https://www.nuget.org/packages/Articulate/4.0.0 , it requires `UmbracoCms.Web (>= 8.0.2 && < 9.0.0)`
