### ISSUE TITLE
Tags and categories pages got 404 Articulate 3.0.2

### ISSUE THREAD

**Issue by arlan85** [Shazwazza/Articulate#312]
Hi, I'm facing with a real problem on my articulate blog. I create my blog with Articulate 3.0.2 on an existing Umbraco 7.7.2 multi language website. I only have one domain with /blog url for blog content. All mi posts pages and list pages works fine except for /tags and /categories list or details pages such as /tags/component, in this cases I get page not found (404). 

Site URL: http://localhost:1234 (200)
Blog URL: http://localhost:1234/blog (200)
Blog List URL: http://localhost:1234/blog/archive (200)
Typical Category URL: http://localhost:1234/blog/tags/component (404)

**Comment by Shazwazza** [comment]
I can see your other posts on Our, if this is the **same** problem  as Craig, then you can see the problem in that Our thread: 

https://our.umbraco.com/packages/starter-kits/articulate/discussions/79901-how-to-get-tags-and-categories-pages-working#comment-255790 ... and an issue has been created for this https://github.com/Shazwazza/Articulate/issues/161

if it is not the same problem then you need to tell me more, what is the domain you have assigned, etc.... essentially what are the exact steps to replicate the problem from a blank install of the latest Umbraco 7.x version and latest Articulate 3.x version.

**Comment by arlan85** [comment]
Hi @Shazwazza, I'm using **Articulate 3.0.2** on an existing **Umbraco 7.7.2** multi language website. If you want to replicate this issue is quite simple. 
I have https://www.domain.com and  https://www.domain.com/es as domains on my site. 
Now, my blog is under /blog and /es/blog. My tags are under /tags and /blog/tags and /es/blog/tags and all of them is get me 404.

**Comment by snoek8** [comment]
I am having the same issue on Umbraco 8. The routing logic probably needs to be adjusted in order to handle multiple languages aside from the multiple article nodes.

**Comment by Shazwazza** [comment]
This is a duplicate issue of https://github.com/Shazwazza/Articulate/issues/161

**Comment by arlan85** [comment]
This still not working, issue #161 is not working for me.

**Comment by Shazwazza** [comment]
@arlan85 Issue #161 is still an open issue - meaning this is not fixed. This issue (312) is a duplicate of 161 which was previously reported and mentioned in the our thread https://our.umbraco.com/packages/starter-kits/articulate/discussions/79901-how-to-get-tags-and-categories-pages-working#comment-256097

**Comment by Shazwazza** [comment]
> I need to solve this problem right away

@arlan85 I cannot guarantee you any time frame that this will be resolved in, i currently don't have any time to work on this. The project is open source so feel free to help out to resolve the issue, submit a PR, debug, etc... 

I'll be fixing this with the latest codebase which is targeting version 4 - which is not the version you are on - once it's fixed and the next 4.x version is out, i can look at backporting the fix to 3.x and releasing that. But again, i don't know when this will be

**Comment by arlan85** [comment]
@Shazwazza no worries, I' ll download the code and take a look. I'll tell you if I found the solution. Thank you for your time and paticence.

**Comment by Shazwazza** [comment]
@arlan85 Just so you know i had made a start on this a couple weeks back. I've pushed WIP changes to a branch: https://github.com/Shazwazza/Articulate/commit/fde30b2c63af4bf1e32081357e4a8c603cf0512f
