### ISSUE TITLE
Version 4.0.0 preventing Umbraco 8.1 from booting

### ISSUE THREAD

**Issue by bokmadsen** [Shazwazza/Articulate#313]
When installing v4 in Umbraxco 8.1 it fails with this:

```
[BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Articulate, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Articulate.Routing.VirtualNodeUrlProvider: Method 'GetUrl' in type 'Articulate.Routing.VirtualNodeUrlProvider' from assembly 'Articulate, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass50_0`1.<GetTypes>b__1()
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader)
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)]
   Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) +339
   Umbraco.Web.Composing.ModuleInjector`1.Init(HttpApplication context) +310
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +581
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369 
```
It looks like the GetUrl method in IUrlProvider has changed signature in 8.1

**Comment by Shazwazza** [comment]
Yes it will need to be updated and recompiled and re-released.

**Comment by beriniwlew** [comment]
Looking forward to an update so I can try this in the latest version of Umbraco.

**Comment by ukdiverboi** [comment]
> Looking forward to an update so I can try this in the latest version of Umbraco.

Same here, doing a new build in the latest version of Umbraco but holding off from using this excellent blog plugin until such point it is working again :)

**Comment by steinarmar** [comment]
I am also very excited to try out the the best blog package with the newest Umbraco version!

No pressure though, only admiration @Shazwazza :)

**Comment by Shazwazza** [comment]
Not sure if i'll get any time soon - i'm on holidays from next week. I'm sure it can't be that hard if someone wants to just send a PR to build against 8.1. If anyone can do that i might have time to test/ship before i go, else it's not gonna be till the end of sept.

**Comment by ukdiverboi** [comment]
I will have a look and see if I can sort it in the next couple of days and then send a PR as you say it shouldn't be that difficult to sort 😁

**Comment by bokmadsen** [comment]
I though about creating a PR too, but couldn't quite figure out how to do conditional refs, unlees we need to branch to two releases. It we reference 8.1 then future updates won't work on 8.0

**Comment by Shazwazza** [comment]
I only maintain one active version, if an old one needs to be patched, then it will be patched (this is how all package devs should work ;)

**Comment by ukdiverboi** [comment]
It was actually me who made the changes and created the PR, Visual Studio is associated with a different account for some reason. Have tested locally, installed fine and all is working fine for me in 8.1.2

**Comment by Shazwazza** [comment]
@ukdiverboi 🎉 Thanks a ton! works perfectly :) I will get this released

**Comment by beriniwlew** [comment]
I'm still having some issues with this.

Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Articulate, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:

**Comment by beriniwlew** [comment]
Is the 4.0.0 version still up?  It says it's that when I go to install, and I'm still having an issue installing.

**Comment by Shazwazza** [comment]
@beriniwlew yes 4.0.0 is still there, if the back office isn't installing the right version correctly it was probably due to some timing/indexing delay on Our. I've just tested and it works fine in a new 8.1.2 installation.
