### ISSUE TITLE
Wrong 'doauth-url' in MarkdownEditor, preventing login when submitting using /a-new

### ISSUE THREAD

**Issue by bokmadsen** [Shazwazza/Articulate#315]
In [MarkdownEditor.cshtml](https://github.com/Shazwazza/Articulate/blob/0d6b0acf073eb4103fc849e8c167eef8fa365392/src/Articulate.Web/App_Plugins/Articulate/Views/MarkdownEditor.cshtml#L177) the doauth-url attribute is wrongly set to @Model.PostUrl, instead of @Model.DoAuthUrl. This prevents successful submission if you're not logged-in in advance

**Comment by Shazwazza** [comment]
Thanks! and sorry for the delay, will get a new release out asap.
