### ISSUE TITLE
number 1 and 2 in the rich text editor content engages umbraco shortcuts

### ISSUE THREAD

**Issue by EnterpriseWide** [Shazwazza/Articulate#318]
When I create a new rich text blog post, i cannot use numbers when typing in the content property. When i type the number 2 in the content property, it changes to the info tab and if i type 1 i get taken back to the content tab. It might be something on my install but I wanted to see if anybody else has the problem as well.
If i type in the number 3, it works as expected

**Comment by Shazwazza** [comment]
That sounds very odd, articulate doesn't do anything with shortcuts so i can only imaging this is some odd thing happening within Umbraco. Can you replicate in Umbraco without articulate and a normal rich text editor?
