### ISSUE TITLE
Rss feed url for tag/category breaks when the tag/category contains a hyphen

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Articulate#32]

**Comment by jfcouturier** [comment]
I use 1.08. 

When I access http://url/blog.aspx/tags and I try to click on one RSS page, I get a bad URL like http://url/blog-aspx/tags/brightwork instead of http://url/blog.aspx/tags/brightwor.

Somewhere, the code change blog.aspx to blog-aspx and we get an error 404

**Comment by Shazwazza** [comment]
@jfcouturier Articulate has never been tested with .Net extensions (i.e. aspx), normally Umbraco is run with extensionless paths since they are much nicer. You should probably change your Umbraco install to use extensionless path's, otherwise you'll have to wait until I have time to look into that. This is also a different issue, if you need this to work, please create a new issue with steps to reproduce.

**Comment by jfcouturier** [comment]
OK thanks. we have changed our umbraco install and it work fine now!
