### ISSUE TITLE
How to associate an image with each Category tag?

### ISSUE THREAD

**Issue by lcichanowicz** [Shazwazza/Articulate#320]
Greetings.  I am trying to figure out a way to associate an image with each blog article Category tag. My ideas seem like sub-optimal workarounds.  Can anyone offer guidance?  We are using blog article categories as filters, and we need their associated images to be content managed.

![image](https://user-images.githubusercontent.com/4871064/66321672-f57d4980-e8ee-11e9-8cde-31a802872ec5.png)

**Comment by Shazwazza** [comment]
Hi, this functionality doesn't exist within Umbraco or Articulate. Articulate just uses Umbraco tags, it doesn't do anything fancy with them. If you wanted to add an icon or other metadata to an Umbraco tag, you'll need to extend the database and create an editor for that.

For example, you could create a new DB table that is a 1:1 relation with the cmsTags table that adds columns for whatever metadata you want. You'll then need to create some sort of tags editor UI to fill in this data.
