### ISSUE TITLE
Modifications to CSS in Phantom theme ignored

### ISSUE THREAD

**Issue by cdecinko** [Shazwazza/Articulate#321]
The Phantom theme does not appear to be using the styles in the Assets/css folder. Unable to locate where I can modify the theme's styles.

**Comment by Shazwazza** [comment]
are you running with debug=false - meanting that CDF is bundling/caching assets (so modifications are not seen unless you bump the cdf version)?

**Comment by cdecinko** [comment]
Yeah, that was it. I had to turn on debug otherwise I was always seeing the cached/bundled version.

**Comment by Shazwazza** [comment]
yep for developing be sure debug=true
