### ISSUE TITLE
Installed package shows version 3.0.0 instead of correct one (4.1.1)

### ISSUE THREAD

**Issue by simonech** [Shazwazza/Articulate#324]
The installed package screen in Umbraco shows 3.0.0 instead of 4.1.1.
Package installed via NuGet

![image](https://user-images.githubusercontent.com/61557/68803336-d7c6a100-065f-11ea-8a9c-5d8f79e65489.png)

**Comment by Shazwazza** [comment]
Pretty sure that info comes from the installpackages.config, not from articulate itself, you'll probably see a few versions listed in there, can't remember how Umbraco decides which one to use, but let me know if I'm wrong :)

**Comment by simonech** [comment]
I never installed any other version on that instance, just 4.1 and then 4.1.1, and both via Nuget
And indeed, the `installedPackages.config` file contains only one reference, of version 3.0.0
And nothing is in the createdPackages.config

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="1" version="3.0.0" url="https://github.com/Shandem/Articulate/" name="Articulate" packagePath="" iconUrl="https://raw.githubusercontent.com/Shazwazza/Articulate/master/assets/Icon-transparent.png" umbVersion="8.0.0" packageGuid="7117d86f-eda5-40e3-aac1-d11aea796715" view="~/App_Plugins/Articulate/BackOffice/PackageOptions/package-options.html">
    <license url="http://opensource.org/licenses/MIT"><![CDATA[MIT License]]></license>
    <author url="http://shazwazza.com"><![CDATA[Shannon Deminick]]></author>
    <contributors />
    <readme><![CDATA[<br/>Blogging built on Umbraco - Supports all the features you'd want in a blogging platform:<br/><br/>
Categories & Tags<br/>
....
```
Don't know how the `installedPackages `file gets updated with packages are installed via NuGet, but maybe some file still references 3.0.0 as version number?
