### ISSUE TITLE
Tags/Categories with certain "Special Characters" causing 500: A potentially dangerous Request.Path value was detected from the client 

### ISSUE THREAD

**Issue by ewilkin7** [Shazwazza/Articulate#325]
Currently on 3.0.2 (just updated from 2.x) - Umbraco 7.15.3.

To recreate: create a tag named "Test: 1". The ":" is encoded to &13a, which still throws the error. 
Can the umbracoSettings.config URL character replacement rules apply to the generated tag? (Similar to how nodes Names are cleaned while creating the node URL)

Any chance this could go to a 3.0.3 build (clients staying on 7.15.3)?

((or, can tags with special characters be prevented somehow))

My temporary workaround is to add in web.config to the tag/categories location path:
<httpRuntime requestPathInvalidCharacters="" />

**Comment by Shazwazza** [comment]
Hi, tags are handled internally by Umbraco, not Articulate. Articulate just uses the tag behavior provided by Umbraco out of the box so you'll want to log an issue with Umbraco itself.

You can probably work around the issue using ContentService.Saving event and change special chars to something else before it's persisted.
