### ISSUE TITLE
Articulate Search - inconsistent search results per page.

### ISSUE THREAD

**Issue by Garetha01** [Shazwazza/Articulate#327]
Umbraco: 7.6.1 - Articulate: 3.0.2

I have the blog page with standard search. When results are returned, each page (paginated) display's a random number of results. eg Page1:4, Page2:3, Page3:4, Page4:3, Page5:5, ... never the same sequence per search.

Are the 'results per page' set somewhere? or is this a bug, or have I screwed something up?.

**Comment by Shazwazza** [comment]
What is the theme you are using? and can you replicate the issue from a vanilla install? The results count per page can be configured on the articulate root node (page size IIRC)

**Comment by Garetha01** [comment]
Hi Shannon, I am using a seriously customized theme (http://new.apimagazine.com.au/articles/), think it was originally based on VAPOR but that was a long time ago. I'm thinking it must be some of the logic I am running in the list template as I have another (more basic site) where the search results are working consistently. I'll systematically remove stuff till it works. Thank you for your time.

**Comment by Garetha01** [comment]
Hey Shannon, rebuilt the Examine indexes and it all works now. - we had imported a whole lot of articles and even though we had re-published the whole blog & subpages they obviously had not been indexed correctly.
