### ISSUE TITLE
ContentType with alias 'ArticulatePost' has an invalid composition

### ISSUE THREAD

**Issue by gordonsaxby** [Shazwazza/Articulate#329]
I am trying to upgrade from 2.0.5 to 3.0.2 in Umbraco v7.15.3

Using a downloaded zip file, I get the following error during the installation:

> ContentType with alias 'ArticulatePost' has an invalid composition and there was a conflict on the following PropertyTypes: 'umbracourlalias, umbracourlname'. PropertyTypes must have a unique alias across all Compositions in order to compose a valid ContentType Composition.

**Comment by Shazwazza** [comment]
Upgrading can be tricky, there's some docs on upgrading here https://github.com/Shazwazza/Articulate/releases/tag/v3.0.0

Perhaps you have modified the original document types?

**Comment by gordonsaxby** [comment]
Yes, the ArticulatePost DocType has been updated, because Articulate has been incorporated into an existing site. I needed to add a tab with some properties.

This issue was a while ago now - as far as I remember, I could not get the upgrade installation to work, but it either did enough for our purposes or I copied DLLs manually - I can't remember now.
