### ISSUE TITLE
Articulate Rich Text and Articulate Markdown are showing 404

### ISSUE THREAD

**Issue by jericyuen** [Shazwazza/Articulate#333]
Umbraco 8.5.3 - Cloud

Articulate - 4.1.1

One of my colleague had installed Articulate onto our cloud project, it works well on Dev, but it doesn't on Live, the Articulate list page loads alright, but the target blog post / article post are showing 404.

I've checked that all the views from Articulate and binaries are all deployed, content are also deployed from Dev to Live using Umbraco Deploy which is good.

But the target page is still on 404. Any idea?

Further checks, I've cloned down the Live site's code from Cloud, I've backup the Live DB as bacpac and then restore them onto my local SSMS and repoint the local cloned down code to this DB. 

I've then tested the article post page and it loads fine. So I can't tell if there's issue with Articulate or the Live Cloud Environment. I've contacted the Umbraco Cloud support and has been told to post it here

**Comment by simonech** [comment]
Have you tried restarting the environment on Cloud? I remember I had some issues in the past with some virtual routes not correctly registered after a Deploy.

**Comment by jericyuen** [comment]
@simonech Let me try that out, let you know in a sec

**Comment by jericyuen** [comment]
@simonech restarted the Live Cloud, still the same

**Comment by jericyuen** [comment]
I've found out what's the issue, on **LIVE**, there's a culture and hostname settings on Homepage which comes with the live url domain and my Articulate Document Type sits outside this Homepage (or on the same level with Homepage) so it's in 404 all the time. 

Upon moving it inside the Homepage, it all works accordingly. 

Posting it here just in case other people is having the same issue

**Comment by Shazwazza** [comment]
Glad you got it solved!
