### ISSUE TITLE
Stackoverflow exception when enabling yyyy/mm/dd url in blog with existing posts

### ISSUE THREAD

**Issue by wvdweerd** [Shazwazza/Articulate#334]
Setup:
Fresh install of Umbraco 8.5.4 with default starter kit (but "Blog" in starter kit renamed to BlogStarterKit to avoid url clash with Articulate blog) + Articulate 4.1.1 installed as package in Umbraco backoffice.

Everything works fine, the blog list showing the 2 included example blog posts.

Then switch/enable the Articulate setting "Use yyyy/mm/dd format for Url".
Now browse to the blog ("/blog") again and the exception occurs.

**Comment by Shazwazza** [comment]
Thanks for reporting, i haven't used this setting for a very long time. I won't have time to look into this anytime soon but it should be pretty easy to debug. I'll mark this as "help wanted" so if you or anyone else can help find and resolve the issue that would be amazing!

**Comment by wvdweerd** [comment]
If I can find some time, I'll try to help.
Otherwise it is at least good for others to know that this issue exists :-)

**Comment by benjaminhowarth1** [comment]
I'm also having a StackOverflowException but when trying to access a post.Url inside a regular loop. Mini theme, existing blog content migrated from V7.

**Comment by benjaminhowarth1** [comment]
Pinpointed the fix & submitted a PR!

**Comment by Shazwazza** [comment]
Nice, i've discovered another issue when testing that I've just fixed too https://github.com/Shazwazza/Articulate/issues/336
