### ISSUE TITLE
Model.BlogBanner is suddenly always empty

### ISSUE THREAD

**Issue by frederiktoft** [Shazwazza/Articulate#338]
Using Umbraco 8.6.3 and Articulate 4.1.2.
In general I've been having a lot of issues after enabling languages, and one is that Model.BlogBanner is suddenly always empty. It was working fine before and I have not touched anything about the blogbanner, but after I started having issues with translations (mentioned in another issue I made here) it is now always empty.

**Comment by Shazwazza** [comment]
Perhaps this is related to trying variants with articulate. Without more details i can't really help with this unless you have steps to replicate. Feel free to reopen if you can supply steps to replicate this one.
