### ISSUE TITLE
Update the Markdown parser and articulate markdown data type to support nicely formatted code

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Articulate#341]
I think the MD parser could do with a lot of help especially when using code blocks. I can't recall if articulate ships with it's own md processors or if it just relies on Umbraco's but it's not great.

It would be great to support code blocks with hints like GH supports: like ```cs 

but it doesn't. Also the code blocks rendered use &#x3C;p&#x3E;&#x3C;code&#x3E; instead of &#x3C;p&#x3E;&#x3C;pre&#x3E;&#x3C;code&#x3E; which is not correct.

Anyways, seems like a lot to be desired :)

**Comment by simonech** [comment]
That has always bothered me. Would be great to have Githib-like rendering for code blocks.
I can have a look at it in the next weeks.

**Comment by Shazwazza** [comment]
Sounds awesome!

**Comment by Shazwazza** [comment]
This is working with rev: 40ada4e5cfa65bc6e9eae73c35dfae057453bda7

Things TODO:

* Update the nuspec to include the additional dependencies (markdig and WebStoating.Markdig.Prism)
* Update the other themes to include the Prism client libs from cdn
* Update the umbraco package xml to ensure that the articulate Articulate.MarkdownEditor is used instead of the Umbraco.MarkdownEditor for data types and property types
* Update the upgrader to change the ArticulateMarkdown data type to use the Articulate.MarkdownEditor

Since this is based on Prism it is very easy for people to restyle however they want.
