### ISSUE TITLE
BlogBanner is always empty

### ISSUE THREAD

**Issue by frederiktoft** [Shazwazza/Articulate#346]
So this is an odd one, because I can't really provide any exception messages and the like. So since I have to release the blog, I have removed all language variation options which I have posted issues of here before. There was still an error creating the articulate root node because it could not automatically create the two child nodes. But I created them manually and it works fine now.
The issue now is that BlogBanner is empty when a page is loaded. The image is displayed fine in the backoffice, and the file is present in the media folder, but when I load a page the model property "BlogBanner" is always empty. I have had this issue before and I think it started when I began to use language variations. But now that I have stopped using that feature the error still persists.
The problem is also I have no idea where to look or what information to give that can help track down the bug. 
Where should I start looking? I will try and provide any information necessary.
It's a basic installation, no other modifications has been made to umbraco other than installing articulate, adding a custom articulate theme, enabling language variations and disabling language variations again. No other code has been changed, modified or other packages has been installed.

**Comment by Shazwazza** [comment]
I am looking into this now since I've seen the same issue even with the latest fixes for variants. 

The `BlogBanner` code is just using this code `RootBlogNode.GetCropUrl(propertyAlias: "blogBanner", imageCropMode: ImageCropMode.Max);` but that doesn't seem to work when variants are enabled even if this property type is invariant. 

I'm trying to see if this is an Umbraco issue or if it's fixed in later Umbraco versions. What Umb version are you using?

**Comment by Shazwazza** [comment]
It looks like Umbraco's GetMediaUrl doesn't work for this scenario. I guess this just shows that not many things use the image cropper directly on a content item. Ideally articulate doesn't do this either but that is a larger change (see https://github.com/Shazwazza/Articulate/pull/342) 

I've created an issue here https://github.com/umbraco/Umbraco-CMS/issues/9608

In the meantime I can manually patch Articulate.

**Comment by frederiktoft** [comment]
A bit late (a lot) but thanks for fixing it :) h5yr
