### ISSUE TITLE
Categories and Tags: Invalid category or invalid tag URL returns index view (status 200) and should throw/return 404 not found

### ISSUE THREAD

**Issue by keitharowe** [Shazwazza/Articulate#347]
### Summary  I expected that if an invalid category or tag passed via URL to the category or tag view; a 404 page should be returned. However, it appears that the default index view is returned (status code 200) instead.

Articulate version tested under 4.1.2 and 4.1.1 - I suspect other versions as well

**Example:** Assuming a fresh install with sample posts, these URLS: tags/cafe or categories/Articulate both return a view with posts. This is expected.
URLS: tags/examplenotvalid or categories/examplenotvalid return a 200 status code and the default index. This is not expected. 

**Why is it important to a proper 404?** 
For SEO reasons, we do not want a 200 page returned for an infinite number of bogus URLs; furthermore, this was discovered from a pesky software security scan testing _Cross-site scripting_. For example this URL: categories/%27%22%20ns%3dnetsparker(0x0805F7)%20 is not sanitized properly and yields this in source:

`<meta name="tags" content="'" ns=netsparker(0x0805F7)" />` 

As a potential short-term fix if validation to the data source is too costly, I would argue that any tag or category view that does not return any posts, does not help the user in any fashion and as such, could return a 404 error.

**Comment by Shazwazza** [comment]
Have applied the `help wanted` label in hopes someone is able to help out with this, it should be a pretty simple fix
