### ISSUE TITLE
seochecker not putting the posts into sitemap.xml

### ISSUE THREAD

**Issue by garrybain** [Shazwazza/Articulate#351]
I notice this was an issue from years ago (2016) and I've had my Umbraco 7 sites be able to produce a sitemap.xml that contains the articulate posts, but using Umbraco 8 does not bring them through into the sitemap.xml file.

Is this a current issue with the latest version of Umbraco and Articulate? 

My document types have the "Exclude in XML sitemap" set to false within seochecker. I understand this could be an seochecker issue as opposed to Articulate but thought it was worth trying to see if there was a known issue.

versions used: 
articulate 4.1.2
umbraco: 8.3.0
seochecker: 2.9.0

Thanks,
Garry.

**Comment by garrybain** [comment]
Just to mention here, I've also tried Our Friendly Sitemap plugin from Umbraco and this doesn't pick up the Articulate node or articles either as I thought this may be a way around seochecker - but it's doing the exact same.

**Comment by Shazwazza** [comment]
Hi, I'm not familiar with how any sitemap plugins work so I can't really comment on why it does or doesn't work.

Several of Articulate's pages such as categories, tags and others aren't real Umbraco nodes, they are just MVC routes.
