### ISSUE TITLE
Forked, Fresh Clone of Master, Build Fails? 

### ISSUE THREAD

**Issue by YodasMyDad** [Shazwazza/Articulate#357]
I have done a straight forward fork and clone of your master repo. Followed the read me, and opened up the Articulate.sln in VS2019 and tried the build. It fails with the following error?

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The build restored NuGet packages. Build the project again to include these packages in the build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568.	Articulate.Web	C:\Users\lee\Documents\Projects\Articulate\src\Articulate.Web\Articulate.Web.csproj	661	

Typically the link for more information in the error doesn't work 🤦‍♂️... I've tried this twice with fresh clones. Obviously a bit of a blocker for anyone wanting to contribute.

Seems something to do with Microsoft Bcl build. I have checked and both Microsoft.Bcl and Microsoft.Bcl.Build nuget packages are installed and in the packages folder?

```
  <Import Project="..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets" Condition="Exists('..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets')" />
  <Target Name="EnsureBclBuildImported" BeforeTargets="BeforeBuild" Condition="'$(BclBuildImported)' == ''">
    <Error Condition="!Exists('..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets')" Text="This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=317567." HelpKeyword="BCLBUILD2001" />
    <Error Condition="Exists('..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets')" Text="The build restored NuGet packages. Build the project again to include these packages in the build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568." HelpKeyword="BCLBUILD2002" />
  </Target>
```

**Comment by Shazwazza** [comment]
Sorry i think the docs need updating for this https://github.com/Shazwazza/Articulate#contributing

3.  should be to re-install the UmbracoCms package. This is a nuget limitation (or could be blamed on the Umbraco nuget package doing a lot of weird things with static files)

Run:

```
Update-Package UmbracoCms -reinstall
```

**Comment by YodasMyDad** [comment]
Perfect thanks.
