### ISSUE TITLE
Macro error in category pages

### ISSUE THREAD

**Issue by skwiggly** [Shazwazza/Articulate#358]
I seem to be having the same issue described here: https://github.com/Shazwazza/Articulate/issues/29. The macro renders everywhere else in the site, just not in the Articulate section. Debugged and the macro parameter is set correctly. 

Error: 
[InvalidOperationException: Cannot render a macro, no content found by id 2147478096]
   Umbraco.Web.UmbracoComponentRenderer.RenderMacro(Int32 contentId, String alias, IDictionary`2 parameters) in D:\a\1\s\src\Umbraco.Web\UmbracoComponentRenderer.cs:100
   Umbraco.Web.UmbracoHelper.RenderMacro(String alias, Object parameters) in D:\a\1\s\src\Umbraco.Web\UmbracoHelper.cs:167

Umbraco 8.11.1
Articulate 4.2.1

View code:
@Umbraco.RenderMacro("TopNavigation", new { startNodeId = @topNavId })

**Comment by Shazwazza** [comment]
Hi, do you have basic steps to replicate from a vanilla install?

**Comment by skwiggly** [comment]
Don't have steps to reproduce from a standard installation. We worked around this by using partials instead of macros.
