### ISSUE TITLE
Does Articulate specifically support Umbraco 7.7? 

### ISSUE THREAD

**Issue by mashtheweb** [Shazwazza/Articulate#365]
Hi there, 

Does Articulate specifically support Umbraco 7.7? 

I see on the main page that it says that the minimum support for the package is Umbraco v8.12 which is slightly misleading.

It is just to clarify as I am checking the compatbility of the product.

Thanks,

Hon

**Comment by Shazwazza** [comment]
Older version 3.x is, see https://nuget.org/packages/Articulate/3.0.2 (7.7 is VERY old!)

**Comment by Shazwazza** [comment]
What do you mean by "main page"? If you mean this one https://our.umbraco.com/packages/starter-kits/articulate/ it says the min is "8.1.2" not "8.12" which is for the current major. Previous major versions support previous Umbraco major versions. I would strongly recommend upgrading to the latest v7.x 7.7 is incredibly old. It shouldn't be too hard to make that update.

**Comment by mashtheweb** [comment]
Hi there,  I am still considering on the upgrade. Just to check I would like to now if there are any associated risks on using Articulate with my current version of 7.6.1 or 7.7? Thanks, Hon

**Comment by mashtheweb** [comment]
For the previous comment, I mean the main page yes, and it showed 8.1.2 as required minimum, that was why I wanted to query that initially. If it does support 7.6.1 and/or 7.7 as you stated earlier then that it will be reassuring, but as stated are there any known risks involved. Thanks, Hon

**Comment by Shazwazza** [comment]
not sure what 'risks' you want to know about but older versions of Articulate such as ones that support very old versions of Umbraco will not get updates. The bigger risk is to continue using a very old and non-supported Umbraco version with old Articulate versions that won't get updates.
