### ISSUE TITLE
404 On  Tags / Category Page after moving content node from root to multisite node

### ISSUE THREAD

**Issue by NoseBagUK** [Shazwazza/Articulate#385]
Hi,

Umbraco: 8.14.1
Articulate: 4.3.0

I'm getting a 404 when I try to view the Tags or Categories.

This is a multi-tenant site, I'd created the sample nodes and it created them in the root. I'm pretty sure that the tags/categories page worked at this point. I then moved the blog node under the home page node of one of the sites, the list page and blog page work fine, but I get a 404 on the tags/categories.

I've looked at all the articles with similar problems but didn't find anything to help me.

Does the category page have a hidden node in the umbraco content tree perhaps that I might need to update the parent ?

Many thanks in advance for any help

**Comment by Shazwazza** [comment]
Categories and tags are 'virtual nodes' created by custom routes. For multi-root sites in Umbraco, only one root node can have a non-domain assigned. All other root nodes must have a domain assigned for routing to work correctly in Umbraco (and articulate). 

Can you confirm that you have domains assigned to your root nodes and that if you have a root node without a domain, that there is only one of these?

**Comment by FloppyChips** [comment]
I have commented on the PR, I'll let my colleague (NoseBagUK) comment on the above.

**Comment by NoseBagUK** [comment]
Both nodes do have domains set and there are no blank nodes, the articulate blog node is set to inherit as it's sitting under one of the home nodes. It was only the category pages that didn't work, the fix that @FloppyChips has done fixes the issue, would be good to get it into an official release.
