### ISSUE TITLE
Articulate netcore site integration

### ISSUE THREAD

**Issue by nvisage-gf** [Shazwazza/Articulate#419]
What's replaced the PreRenderViewActionFilterAttribute.ActionExecuted feature in netcore, or the recommended pattern for modifying the render model now?

Looking at updating an existing v7 site that tags the Articulate master model onto sites model ref #33.

**Comment by nvisage-gf** [comment]
Posted too soon, using custom theme should suffice, apologies.

**Comment by Shazwazza** [comment]
For upgrading, I think it will probably be easiest to export your blogml (ensure you use the latest Articulate 4 for that) and then start from scratch and re-import your blogml. But you can always try to upgrade in-place but there will be quite a lot of changes needed.
