### ISSUE TITLE
Allow RSS feed to display either full post or the excerpt

### ISSUE THREAD

**Issue by naepalm** [Shazwazza/Articulate#44]
I couldn't find this anywhere, so I thought I'd make an issue - it would be really great if we could select whether we want our RSS feed to populate the full post or just an excerpt of the post.

**Comment by Shazwazza** [comment]
Have fixed this and #71  :)

You can follow the instructions here: https://github.com/Shazwazza/Articulate/wiki/Configuration#rssfeedgenerator

This will allow you to configure the RSS feed however you would like. 

If you want to just display the excerpt then you can override the `GetPostContent` method of the `RssFeedGenerator` and do this:

     return model.Excerpt.ToHtmlString();
