### ISSUE TITLE
In current version date formated url (blog/2022/07/) giving 404

### ISSUE THREAD

**Issue by RPanc** [Shazwazza/Articulate#447]
I have used this articulate before in umbraco 8 in that version its working fine like blog/2022/07/ if hit this url its filter articles and showing articles which publish date is in month of 07 and year is 2022.
However in never version its giving me 404.
![image](https://github.com/Shazwazza/Articulate/assets/26817328/834ed51f-2923-4083-b817-38246cb2e7a4)

**Comment by Shazwazza** [comment]
You have to enable that setting in the articulate root node IIRC.

**Comment by RPanc** [comment]
It's enable there but I believe this for blogpost not for the list page so I created another content finder which will omit 2022/07/ 
and it will stay on blog node and from url I fetch the month and a year and passing the filtered result to list.

**Comment by Shazwazza** [comment]
Hi, I see this is closed - so is it a bug in Articulate that you had to work around or does it work in Articulate?
