### ISSUE TITLE
newly installed articulate package , clicking on categories or tags gives --> NullReferenceException: Object reference not set to an instance of an object.  

### ISSUE THREAD

**Issue by sangeeta-singh-github** [Shazwazza/Articulate#449]
I've freshly installed Articulate 5.1.0 and have umbraco version 13. Package is successfully installed however everytime I click on categories or tags from the blog home page it redirects me to localhost/categories and gives null reference exception.

What am I missing? 

Also, the search bar gives similar error

![image](https://github.com/Shazwazza/Articulate/assets/127402135/33bf1d79-b969-44aa-9f33-3729bfb3f5e0)

**Comment by Shazwazza** [comment]
Is this on a clean install of Umbraco or do you have a bunch of other packages installed too?

**Comment by sangeeta-singh-github** [comment]
On a clean install of umbraco

**Comment by Shazwazza** [comment]
Interesting, i can replicate, looking into it

**Comment by Shazwazza** [comment]
Fixed in 5.1.1 https://github.com/Shazwazza/Articulate/releases/tag/v5.1.1
