### ISSUE TITLE
How to get the article list of specific category?

### ISSUE THREAD

**Issue by anushuias** [Shazwazza/Articulate#454]
Could anyne tell me how to get the article list under one category in partial views by passing the category name from post.cshtml? I've trying this since last week and no luck yet :(

**Comment by Shazwazza** [comment]
There's nothing specific in Articulate for you to do that but there are some helper methods.

For example, the feature to render all pages by category starts in this controller: https://github.com/Shazwazza/Articulate/blob/f8c59d1007b517cfe7274e0f781a0bc626c3e7e5/src/Articulate/Controllers/ArticulateTagsController.cs#L112

And ends up calling this service method https://github.com/Shazwazza/Articulate/blob/f8c59d1007b517cfe7274e0f781a0bc626c3e7e5/src/Articulate/Services/ArticulateTagService.cs#L28

You could potentially use something like that.
