### ISSUE TITLE
fix for useDomainPrefixes set to true

### ISSUE THREAD

**Issue by shoecake** [Shazwazza/Articulate#55]
If useDomainPrefixes is set in umbraco.settings, then the tag cloud and other areas do not render hyperlinks correctly.

changes I have made to fix are in the attached image

![spc changes to fix usedomainprefixes](https://cloud.githubusercontent.com/assets/8297265/6091849/11e6a8a4-aeb7-11e4-8a79-d345e7a54985.PNG)

**Comment by Shazwazza** [comment]
haha! that's an interesting PR :) I'll review this this week, thx!

**Comment by Shazwazza** [comment]
Hi, I've fixed this in a slightly different way and also found some other issues that I've fixed with domain prefixes.
