### ISSUE TITLE
Uninstall Problems

### ISSUE THREAD

**Issue by katharinewalker** [Shazwazza/Articulate#57]
After uninstalling Articulate 1.0.5 i cannot run umbraco. The umbraco log file shows the following error:-
Error handling creation of PropertyType 'Theme'. Could not find DataTypeDefintion with unique id '8b57d00e-5593-45d3-affe-24203b239bd3' nor one referencing the DataType with a property editor alias (or legacy control id) 'ArticulateThemePicker'. Did the package creator forget to package up custom datatypes? This property will be converted to a label/readonly editor if one exists.
Any ideas?

**Comment by Shazwazza** [comment]
Sorry for the delay on replying to this. 

Have you sorted this out? I cannot replicate this issue. I've installed and uninstalled a few times and do not get this issue occuring.
