### ISSUE TITLE
Author image never null?

### ISSUE THREAD

**Issue by wroughtec** [Shazwazza/Articulate#59]
Even if I don't have an image for the author umbraco still seems to see some data with:
!Model.Author.Image.IsNullOrWhiteSpace()

Is there another option that could be sued when no image used? Or is this a bug?

Umbraco 7.2.2 articulate 1.6

**Comment by Shazwazza** [comment]
It would be most helpful if you can tell me what the data is there?

**Comment by wroughtec** [comment]
Ok  this is what the if statement is:
@if (!Model.Author.Image.IsNullOrWhiteSpace())
 {
@Model.Author.Image
}

/authors/aimee-fuller?mode=max&rnd=130706330100000000
