### ISSUE TITLE
500 Error when importing blogml

### ISSUE THREAD

**Issue by visbuild** [Shazwazza/Articulate#61]
We are trying to use the BlogML import feature in Articulate and getting a 500 error with no useful info (also there is nothing in the log :( )

Is anyone using that feature and not getting an error?

Using umb v7.2.2 and Articulate 1.0.6

This is the file: http://drop.bdvs.info/1gNbT (example file from blogML)

the path called: /umbraco/Api/ArticulateBlogImport/PostImportBlogMl

my network log
![screen shot 2015-03-17 at 11 43 32](https://cloud.githubusercontent.com/assets/10462097/6686595/f45e2526-cc9a-11e4-9403-a352c23cd601.png)

**Comment by Shazwazza** [comment]
This is fixed now, will make a new release today and it works with your sample blogml
