### ISSUE TITLE
Publish a post fails if excerpt is left blank

### ISSUE THREAD

**Issue by davidfhill** [Shazwazza/Articulate#67]
In version 1.0.7
If the "Excerpt" property of a post does not have a value and "Save and publish" is clicked - the post is not published and the "Save and publish" button becomes disabled.
Nothing else can be done until returning to the Archive node (the information in the newly-created post is lost.)
The same thing happens when just clicking "Save".
It doesn't appear to be an issue in version 1.0.5. (I never installed 1.0.6 so I can't say.)

- David Hill

**Comment by Shazwazza** [comment]
Must have been a regression issue with some changes made to the excerpt. I'll fix up and release a new version asap
