### ISSUE TITLE
Unable to preview blog item without publishing?

### ISSUE THREAD

**Issue by StevenWillett** [Shazwazza/Articulate#68]
Hi,

The Articulate Umbraco plugin is fantastic and the only issue we have found thus far is the ability or lack thereof for being able to preview the blog item before publishing?

Is there a feature in the plugin I am unaware of or maybe have missed? or does this feature simply not exist?

Any suggestions appreciated.

**Comment by StevenWillett** [comment]
Going top try this suggestion here: https://our.umbraco.org/projects/starter-kits/articulate/discussions/60562-Preview-Articulate-blog-post?p=0

**Comment by StevenWillett** [comment]
I already had the template assigned to each blog item already so simply assigning the main template to both the Markdown & Rich Text doc types resolved this for me.

"Assign any template to the Articulate Markdown and the Articulate Rich Text document types."

**Comment by Shazwazza** [comment]
The latest 7.2.4 version of  Umbraco fixes this issue so you don't have to assign a random template to get the preview button to show.
