### ISSUE TITLE
BlogML import, post-url="" throws unfriendly error

### ISSUE THREAD

**Issue by Mantaii** [Shazwazza/Articulate#70]
Hi, 
When importing a Blog via BlogML I decided to remove any post-url value to see if Articulate would create its own slug. 

<code>post id="1" date-created="2012-09-25T08:57:25Z" date-modified="2012-09-25T08:56:15Z" approved="true" **post-url=""** type="normal" hasexcerpt="false" views="0" is-published="True"</code>

The import fails and tells you to look at the logs for help. The logs aren't very helpful either and it was just guess work that I tried it again with a post-url value. 

<code>
ERROR Articulate.BlogMlImporter - [Thread 198] Importing failed with errors
System.NullReferenceException: Object reference not set to an instance of an object.
   at Articulate.BlogMlImporter.<ImportPosts>d__1b.MoveNext() in x:\Projects\Articulate\Articulate.Project\Articulate\BlogMlImporter.cs:line 255
</code>

**Comment by Shazwazza** [comment]
The slug is optional (it is actually just umbracoUrlName underneath). But the importer should allow an empty value, will investigate.

**Comment by ScottGuymer** [comment]
I have had a look at this and it seems that the url is always being read and stuffed in umbracoUrlName.

I think there just needs to be a check to see if it is populated and if not just dont try to assign it.


I will add in a null check on the URL and submit a PR.

**Comment by Shazwazza** [comment]
Fixed with PR
