### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by nvisage-gf** [Shazwazza/Articulate#73]
https://github.com/Shazwazza/Articulate/blob/master/Articulate/UmbracoEventHandler.cs#L192

In 7.2.4 with debug=false in web.config this line is causing duplicate key exceptions to be thrown when CMS makes calls to /umbraco/ServerVariables.

Wrapping the Add in an check would resolve?

            if (!e.ContainsKey("articulate"))
            {
                 e.Add("articulate", ......
            }

**Comment by nvisage-gf** [comment]
debug is a red herring, we have output caching disabled if in debug mode. Additionally would a better fix be to always set the key to handle multiple articulate instances?:

 if (!e.ContainsKey("articulate"))
        {
             e.Add("articulate", ......
        } else {
             e.["articulate"] =  ......
        }

**Comment by Shazwazza** [comment]
Yup, needs to be fixed here but also it's an issue in the umb core: http://issues.umbraco.org/issue/U4-6559
