### ISSUE TITLE
Which type of visual studio 2013 project is Articulate project?

### ISSUE THREAD

**Issue by biapar** [Shazwazza/Articulate#76]
Which type of visual studio 2013 project is Articulate project ( Articulate folder )?

**Comment by Shazwazza** [comment]
Articulate = class library
Articulate.Web = web application

**Comment by biapar** [comment]
class library ( not mvc ? ).

**Comment by Shazwazza** [comment]
Articulate = class library
Articulate.Web = web application (where the views are)

You know you can just open the .sln file to see for yourself right?
