### ISSUE TITLE
Insert Macro in RTE missing?

### ISSUE THREAD

**Issue by StevenWillett** [Shazwazza/Articulate#78]
Hi Articulate GitHubbers & Shazwazza,

I think its a config setting but where can i allow the Articulate plugin content nodes to Insert / use of Macro's in the RTE within the Umbraco CMS?

I would like to be able to insert a Macro within our news items which is driven by Articulate.

Any pointers appreciated.

**Comment by StevenWillett** [comment]
Found the solution: 
Developer > Data Types > Articulate Rich Text > Ensure "umbMacro" is selected.

**Comment by Shazwazza** [comment]
Great, glad you found it :)
