### ISSUE TITLE
Upper case

### ISSUE THREAD

**Issue by jfcouturier** [Shazwazza/Articulate#84]
Hi,

When we write @post.Name, each word begin with an upper case. In french, this is not relevant. How can I change this behaviour?

**Comment by vnbaaij** [comment]
Just change to @post.Name.ToLower()

**Comment by jfcouturier** [comment]
Hi Vincent,

It was a css issue:

.widget .content ul {
    list-style-type: none !important;
    margin: 0 !important;
    padding: 0 !important;
    //text-transform: capitalize;
    text-transform: none
}

Thx anyway for the reply. 

Regards
