### ISSUE TITLE
Old categorie

### ISSUE THREAD

**Issue by jfcouturier** [Shazwazza/Articulate#86]
Hi,
I've deleted the testpost but I still see the category TestCategory. How can I reset the categories/tags when I unpublish/delete posts?
Thx for your help

**Comment by Shazwazza** [comment]
What version of Umbraco and articulate are you using? This is a duplicate issue iirc. 
You can empty your recycle bin, but that should be fixed in later Umbraco versions.

**Comment by jfcouturier** [comment]
Version 1.08 of Articulate and Umbraco version 7.2.6 assembly: 1.0.5632.22681.
OK, I've deleted item and the TestCategory is gone.

Thank you!

**Comment by Shazwazza** [comment]
I'll leave it open for now to double check this gets properly fixed.
