### ISSUE TITLE
Tags URL not working with Vietnamese language.

### ISSUE THREAD

**Issue by Ariel-Soft** [Shazwazza/Articulate#88]
Hi Support,

I am using Articulate. It is working fine except tags field.

Actually I am using Vietnamese language in tags input.

When I click on tags on article page it did not open the page where same tags records exist. But when I use English Language in tags then its working fine. It goes to its same tags records page.

I did not understand why articulate not working with "tags url" in some languages.

Please Help. Thanks.

Best Regards, 
Dile Ram

**Comment by Shazwazza** [comment]
Can you tell me which words you are using in your tags that are not working ? 

I've just tested with this word: 

giới

and it works fine.

**Comment by Ariel-Soft** [comment]
Thanks for reply.

I am using "Chính trị - Xã hội" in my tags and it is not working.
actually all keyword that is related to vietnamese language is not working.
Is any solution for this that I can apply in my project.

Thanks

**Comment by Shazwazza** [comment]
Can you please test this with the latest Articulate (and Umbraco version) as i cannot reproduce this issue with those versions using a tag of "Chính trị - Xã hội"  - seems to work.

**Comment by monais** [comment]
@Shazwazza I'm facing issue with Umbraco Multi language website English & Arabic. English (en-US) is working fine as default language. Arabic (ar-SA) secondary language is not working, showing 404 error.
Domains setting with Culture and Hostnames
http://localhost:4865
http://localhost:4865/ar

I did followed all steps in the below link:
https://www.youtube.com/watch?v=-vzxCdjq4FM&ab_channel=UmbracoHQ
