### ISSUE TITLE
Category naming issue

### ISSUE THREAD

**Issue by Syntaxis** [Shazwazza/Articulate#89]
Hi there,

I have an issue related to categories. Basically I think that one of our content editors, when initially adding the category 'Office' to a blog post, had accidentally entered it as 'office' (i.e. without a capital letter 'O'). Because of this, for every subsequent blog post this category was added to it would appear under 'office'.

I thought, OK.. Simple enough.. I added the category 'Office' to a blog post, however this post was still shown under 'office' in the categories page. So then I made a list of all the posts that needed to be categorized under 'Office', removed the 'office' category from all of these, and then re-add the new category 'Office' back on to each of those blog posts. This worked fine on the post-specific category listing on the right-hand side of the post view of each blog post, however on the categories page itself they were still shown under 'office'. All the other categories on this page begin with a capital letter so it makes this one category looks really out of place.

From what I can tell the categories page does not take into account the case-sensitivity of the category names, and thus will treat them as the same category, which in some ways is not too much of an issue in itself however even after removing it from all places and then re-adding it back with the capitalized first letter it would still show all of these posts under 'office', so I presume that even when a category is removed from all places it is still stored in memory somehow. Any ideas on how to sort this? Thanks :)

**Comment by Shazwazza** [comment]
have you restarted your web app after you made these changes (i.e. bump your web.config so the runtime memory is cleared?).

**Comment by Syntaxis** [comment]
Thanks for the reply. I tried that but still no luck :/

**Comment by Shazwazza** [comment]
Hi, very sorry that this issue is so old without a reply. I will close this issue for now since it's not been reported by anyone else and I think later versions of Articulate have potentially already solved the problem. Please re-open if the issue still remains in the latest version of Articulate.
